
----------------
--auto gen proto map file
----------------
PROTO_MAP = {}

CS_HEART = 1
PROTO_MAP[CS_HEART] = "cs_heart"

SC_HEART = 2
PROTO_MAP[SC_HEART] = "sc_heart"

CS_VERSION = 3
PROTO_MAP[CS_VERSION] = "cs_version"

SC_VERSION = 4
PROTO_MAP[SC_VERSION] = "sc_version"

CS_CONFIG = 5
PROTO_MAP[CS_CONFIG] = "cs_config"

SC_CONFIG = 6
PROTO_MAP[SC_CONFIG] = "sc_config"

CS_GM_TEST = 17
PROTO_MAP[CS_GM_TEST] = "cs_gm_test"

SC_GM_TEST = 18
PROTO_MAP[SC_GM_TEST] = "sc_gm_test"

CS_HANDSHAKE = 20
PROTO_MAP[CS_HANDSHAKE] = "cs_handshake"

SC_HANDSHAKE = 21
PROTO_MAP[SC_HANDSHAKE] = "sc_handshake"

SC_RESET_ZERO = 36
PROTO_MAP[SC_RESET_ZERO] = "sc_reset_zero"

CS_NOTICE_MSG = 44
PROTO_MAP[CS_NOTICE_MSG] = "cs_notice_msg"

SC_NOTICE_MSG = 45
PROTO_MAP[SC_NOTICE_MSG] = "sc_notice_msg"

CS_GIFT_DRAW = 47
PROTO_MAP[CS_GIFT_DRAW] = "cs_gift_draw"

SC_GIFT_DRAW = 48
PROTO_MAP[SC_GIFT_DRAW] = "sc_gift_draw"

SC_BROADCAST_MSG = 49
PROTO_MAP[SC_BROADCAST_MSG] = "sc_broadcast_msg"

CS_ACCOUNT_LOGIN = 10001
PROTO_MAP[CS_ACCOUNT_LOGIN] = "cs_account_login"

SC_ACCOUNT_LOGIN = 10002
PROTO_MAP[SC_ACCOUNT_LOGIN] = "sc_account_login"

CS_ACCOUNT_CREATE = 10003
PROTO_MAP[CS_ACCOUNT_CREATE] = "cs_account_create"

SC_ACCOUNT_CREATE = 10004
PROTO_MAP[SC_ACCOUNT_CREATE] = "sc_account_create"

SC_ACCOUNT_KICK = 10005
PROTO_MAP[SC_ACCOUNT_KICK] = "sc_account_kick"

CS_ROLE_INFO = 10101
PROTO_MAP[CS_ROLE_INFO] = "cs_role_info"

SC_ROLE_INFO = 10102
PROTO_MAP[SC_ROLE_INFO] = "sc_role_info"

SC_ROLE_EXP_NOTIFY = 10104
PROTO_MAP[SC_ROLE_EXP_NOTIFY] = "sc_role_exp_notify"

CS_ROLE_PUBLIC = 10105
PROTO_MAP[CS_ROLE_PUBLIC] = "cs_role_public"

SC_ROLE_PUBLIC = 10106
PROTO_MAP[SC_ROLE_PUBLIC] = "sc_role_public"

CS_ROLE_EXTRA = 10108
PROTO_MAP[CS_ROLE_EXTRA] = "cs_role_extra"

SC_ROLE_EXTRA = 10109
PROTO_MAP[SC_ROLE_EXTRA] = "sc_role_extra"

SC_ROLE_ENERGY_NOTIFY = 10111
PROTO_MAP[SC_ROLE_ENERGY_NOTIFY] = "sc_role_energy_notify"

SC_ROLE_POWER_NOTIFY = 10112
PROTO_MAP[SC_ROLE_POWER_NOTIFY] = "sc_role_power_notify"

CS_ROLE_OPTIONS = 10113
PROTO_MAP[CS_ROLE_OPTIONS] = "cs_role_options"

SC_ROLE_OPTIONS = 10114
PROTO_MAP[SC_ROLE_OPTIONS] = "sc_role_options"

CS_ROLE_SETOPT = 10116
PROTO_MAP[CS_ROLE_SETOPT] = "cs_role_setopt"

SC_ROLE_SETOPT = 10117
PROTO_MAP[SC_ROLE_SETOPT] = "sc_role_setopt"

CS_ROLE_SETICON = 10118
PROTO_MAP[CS_ROLE_SETICON] = "cs_role_seticon"

SC_ROLE_SETICON = 10119
PROTO_MAP[SC_ROLE_SETICON] = "sc_role_seticon"

CS_ROLE_BUY_ENERGY = 10120
PROTO_MAP[CS_ROLE_BUY_ENERGY] = "cs_role_buy_energy"

SC_ROLE_BUY_ENERGY = 10121
PROTO_MAP[SC_ROLE_BUY_ENERGY] = "sc_role_buy_energy"

CS_ROLE_EXP_EFFECT = 10122
PROTO_MAP[CS_ROLE_EXP_EFFECT] = "cs_role_exp_effect"

SC_ROLE_EXP_EFFECT = 10123
PROTO_MAP[SC_ROLE_EXP_EFFECT] = "sc_role_exp_effect"

CS_ROLE_FIGHTERS = 10124
PROTO_MAP[CS_ROLE_FIGHTERS] = "cs_role_fighters"

SC_ROLE_FIGHTERS = 10125
PROTO_MAP[SC_ROLE_FIGHTERS] = "sc_role_fighters"

SC_ROLE_SKILLPOINT_NOTIFY = 10126
PROTO_MAP[SC_ROLE_SKILLPOINT_NOTIFY] = "sc_role_skillpoint_notify"

CS_ROLE_CLICK_GOLD = 10127
PROTO_MAP[CS_ROLE_CLICK_GOLD] = "cs_role_click_gold"

SC_ROLE_CLICK_GOLD = 10128
PROTO_MAP[SC_ROLE_CLICK_GOLD] = "sc_role_click_gold"

SC_ROLE_FIRSTATK_UPDATE = 10129
PROTO_MAP[SC_ROLE_FIRSTATK_UPDATE] = "sc_role_firstatk_update"

CS_ROLE_BUY_SKILLPOINT = 10130
PROTO_MAP[CS_ROLE_BUY_SKILLPOINT] = "cs_role_buy_skillpoint"

SC_ROLE_BUY_SKILLPOINT = 10131
PROTO_MAP[SC_ROLE_BUY_SKILLPOINT] = "sc_role_buy_skillpoint"

CS_ROLE_FIRSTATK_UPDATE = 10132
PROTO_MAP[CS_ROLE_FIRSTATK_UPDATE] = "cs_role_firstatk_update"

SC_ROLE_MINEENERGY_NOTIFY = 10133
PROTO_MAP[SC_ROLE_MINEENERGY_NOTIFY] = "sc_role_mineenergy_notify"

CS_ROLE_BUY_MINEENERGY = 10134
PROTO_MAP[CS_ROLE_BUY_MINEENERGY] = "cs_role_buy_mineenergy"

SC_ROLE_BUY_MINEENERGY = 10135
PROTO_MAP[SC_ROLE_BUY_MINEENERGY] = "sc_role_buy_mineenergy"

CS_ROLE_RENAME = 10136
PROTO_MAP[CS_ROLE_RENAME] = "cs_role_rename"

SC_ROLE_RENAME = 10137
PROTO_MAP[SC_ROLE_RENAME] = "sc_role_rename"

CS_ROLE_OPENHCARD = 10138
PROTO_MAP[CS_ROLE_OPENHCARD] = "cs_role_openhcard"

SC_ROLE_OPENHCARD = 10139
PROTO_MAP[SC_ROLE_OPENHCARD] = "sc_role_openhcard"

CS_FIGHT_DEMO = 10206
PROTO_MAP[CS_FIGHT_DEMO] = "cs_fight_demo"

SC_FIGHT_DEMO = 10207
PROTO_MAP[SC_FIGHT_DEMO] = "sc_fight_demo"

CS_FIGHT_DEMO_REPORT = 10208
PROTO_MAP[CS_FIGHT_DEMO_REPORT] = "cs_fight_demo_report"

CS_SHOP_LIST = 10301
PROTO_MAP[CS_SHOP_LIST] = "cs_shop_list"

SC_SHOP_LIST = 10302
PROTO_MAP[SC_SHOP_LIST] = "sc_shop_list"

SC_SHOP_NOTIFY = 10305
PROTO_MAP[SC_SHOP_NOTIFY] = "sc_shop_notify"

CS_SHOP_BUY = 10306
PROTO_MAP[CS_SHOP_BUY] = "cs_shop_buy"

SC_SHOP_BUY = 10307
PROTO_MAP[SC_SHOP_BUY] = "sc_shop_buy"

CS_SHOP_REFRESH = 10308
PROTO_MAP[CS_SHOP_REFRESH] = "cs_shop_refresh"

SC_SHOP_REFRESH = 10309
PROTO_MAP[SC_SHOP_REFRESH] = "sc_shop_refresh"

CS_SHOP_WAKE_ONEDRAW = 10310
PROTO_MAP[CS_SHOP_WAKE_ONEDRAW] = "cs_shop_wake_onedraw"

SC_SHOP_WAKE_ONEDRAW = 10311
PROTO_MAP[SC_SHOP_WAKE_ONEDRAW] = "sc_shop_wake_onedraw"

CS_SHOP_WAKE_TENDRAW = 10312
PROTO_MAP[CS_SHOP_WAKE_TENDRAW] = "cs_shop_wake_tendraw"

SC_SHOP_WAKE_TENDRAW = 10313
PROTO_MAP[SC_SHOP_WAKE_TENDRAW] = "sc_shop_wake_tendraw"

CS_GER_LIST = 10401
PROTO_MAP[CS_GER_LIST] = "cs_ger_list"

SC_GER_LIST = 10402
PROTO_MAP[SC_GER_LIST] = "sc_ger_list"

SC_GER_NOTIFY = 10404
PROTO_MAP[SC_GER_NOTIFY] = "sc_ger_notify"

CS_GER_UNLOCK = 10405
PROTO_MAP[CS_GER_UNLOCK] = "cs_ger_unlock"

SC_GER_UNLOCK = 10406
PROTO_MAP[SC_GER_UNLOCK] = "sc_ger_unlock"

CS_GER_STANDUP = 10407
PROTO_MAP[CS_GER_STANDUP] = "cs_ger_standup"

SC_GER_STANDUP = 10408
PROTO_MAP[SC_GER_STANDUP] = "sc_ger_standup"

CS_GER_MOVPOS = 10409
PROTO_MAP[CS_GER_MOVPOS] = "cs_ger_movpos"

SC_GER_MOVPOS = 10410
PROTO_MAP[SC_GER_MOVPOS] = "sc_ger_movpos"

CS_GER_UPLEVEL = 10413
PROTO_MAP[CS_GER_UPLEVEL] = "cs_ger_uplevel"

SC_GER_UPLEVEL = 10414
PROTO_MAP[SC_GER_UPLEVEL] = "sc_ger_uplevel"

CS_GER_UPRANK = 10415
PROTO_MAP[CS_GER_UPRANK] = "cs_ger_uprank"

SC_GER_UPRANK = 10416
PROTO_MAP[SC_GER_UPRANK] = "sc_ger_uprank"

CS_GER_UPSTAR = 10419
PROTO_MAP[CS_GER_UPSTAR] = "cs_ger_upstar"

SC_GER_UPSTAR = 10420
PROTO_MAP[SC_GER_UPSTAR] = "sc_ger_upstar"

CS_GER_UPSKILL = 10421
PROTO_MAP[CS_GER_UPSKILL] = "cs_ger_upskill"

SC_GER_UPSKILL = 10422
PROTO_MAP[SC_GER_UPSKILL] = "sc_ger_upskill"

CS_GER_STAGE_UPRANK = 10423
PROTO_MAP[CS_GER_STAGE_UPRANK] = "cs_ger_stage_uprank"

SC_GER_STAGE_UPRANK = 10424
PROTO_MAP[SC_GER_STAGE_UPRANK] = "sc_ger_stage_uprank"

CS_GER_STAGE_CHOSE = 10425
PROTO_MAP[CS_GER_STAGE_CHOSE] = "cs_ger_stage_chose"

SC_GER_STAGE_CHOSE = 10426
PROTO_MAP[SC_GER_STAGE_CHOSE] = "sc_ger_stage_chose"

SC_GER_LINE_NOTIFY = 10431
PROTO_MAP[SC_GER_LINE_NOTIFY] = "sc_ger_line_notify"

CS_GER_PIECE_EXCHANGE = 10432
PROTO_MAP[CS_GER_PIECE_EXCHANGE] = "cs_ger_piece_exchange"

SC_GER_PIECE_EXCHANGE = 10433
PROTO_MAP[SC_GER_PIECE_EXCHANGE] = "sc_ger_piece_exchange"

CS_GER_SET_LINE = 10437
PROTO_MAP[CS_GER_SET_LINE] = "cs_ger_set_line"

SC_GER_SET_LINE = 10438
PROTO_MAP[SC_GER_SET_LINE] = "sc_ger_set_line"

CS_GER_LINE_LIST = 10439
PROTO_MAP[CS_GER_LINE_LIST] = "cs_ger_line_list"

SC_GER_LINE_LIST = 10440
PROTO_MAP[SC_GER_LINE_LIST] = "sc_ger_line_list"

CS_GER_LINE_UNLOCK = 10441
PROTO_MAP[CS_GER_LINE_UNLOCK] = "cs_ger_line_unlock"

SC_GER_LINE_UNLOCK = 10442
PROTO_MAP[SC_GER_LINE_UNLOCK] = "sc_ger_line_unlock"

CS_GER_CLOTHE = 10443
PROTO_MAP[CS_GER_CLOTHE] = "cs_ger_clothe"

SC_GER_CLOTHE = 10444
PROTO_MAP[SC_GER_CLOTHE] = "sc_ger_clothe"

CS_MAIL_INFO = 10502
PROTO_MAP[CS_MAIL_INFO] = "cs_mail_info"

SC_MAIL_INFO = 10503
PROTO_MAP[SC_MAIL_INFO] = "sc_mail_info"

CS_MAIL_MORE = 10504
PROTO_MAP[CS_MAIL_MORE] = "cs_mail_more"

SC_MAIL_MORE = 10505
PROTO_MAP[SC_MAIL_MORE] = "sc_mail_more"

CS_MAIL_READ = 10506
PROTO_MAP[CS_MAIL_READ] = "cs_mail_read"

SC_MAIL_READ = 10507
PROTO_MAP[SC_MAIL_READ] = "sc_mail_read"

CS_MAIL_DRAW = 10508
PROTO_MAP[CS_MAIL_DRAW] = "cs_mail_draw"

SC_MAIL_DRAW = 10509
PROTO_MAP[SC_MAIL_DRAW] = "sc_mail_draw"

CS_MAIL_DELETE = 10510
PROTO_MAP[CS_MAIL_DELETE] = "cs_mail_delete"

SC_MAIL_DELETE = 10511
PROTO_MAP[SC_MAIL_DELETE] = "sc_mail_delete"

SC_MAIL_NEW = 10512
PROTO_MAP[SC_MAIL_NEW] = "sc_mail_new"

CS_EQUIP = 10604
PROTO_MAP[CS_EQUIP] = "cs_equip"

SC_EQUIP = 10605
PROTO_MAP[SC_EQUIP] = "sc_equip"

SC_EQUIP_NOTIFY = 10608
PROTO_MAP[SC_EQUIP_NOTIFY] = "sc_equip_notify"

CS_EQUIP_UPLEVEL = 10617
PROTO_MAP[CS_EQUIP_UPLEVEL] = "cs_equip_uplevel"

SC_EQUIP_UPLEVEL = 10618
PROTO_MAP[SC_EQUIP_UPLEVEL] = "sc_equip_uplevel"

CS_EQUIP_UPRANK = 10619
PROTO_MAP[CS_EQUIP_UPRANK] = "cs_equip_uprank"

SC_EQUIP_UPRANK = 10620
PROTO_MAP[SC_EQUIP_UPRANK] = "sc_equip_uprank"

CS_EQUIP_UPSTAR = 10621
PROTO_MAP[CS_EQUIP_UPSTAR] = "cs_equip_upstar"

SC_EQUIP_UPSTAR = 10622
PROTO_MAP[SC_EQUIP_UPSTAR] = "sc_equip_upstar"

CS_EQUIP_EAT = 10623
PROTO_MAP[CS_EQUIP_EAT] = "cs_equip_eat"

SC_EQUIP_EAT = 10624
PROTO_MAP[SC_EQUIP_EAT] = "sc_equip_eat"

CS_MONEY_INFO = 10801
PROTO_MAP[CS_MONEY_INFO] = "cs_money_info"

SC_MONEY_INFO = 10802
PROTO_MAP[SC_MONEY_INFO] = "sc_money_info"

SC_MONEY_NOTIFY = 10804
PROTO_MAP[SC_MONEY_NOTIFY] = "sc_money_notify"

CS_MONEY_OPENBOX = 10805
PROTO_MAP[CS_MONEY_OPENBOX] = "cs_money_openbox"

SC_MONEY_OPENBOX = 10806
PROTO_MAP[SC_MONEY_OPENBOX] = "sc_money_openbox"

CS_MONEY_SELL = 10807
PROTO_MAP[CS_MONEY_SELL] = "cs_money_sell"

SC_MONEY_SELL = 10808
PROTO_MAP[SC_MONEY_SELL] = "sc_money_sell"

CS_MONEY_BUY = 10809
PROTO_MAP[CS_MONEY_BUY] = "cs_money_buy"

SC_MONEY_BUY = 10810
PROTO_MAP[SC_MONEY_BUY] = "sc_money_buy"

CS_PVP_GET_LIST = 10901
PROTO_MAP[CS_PVP_GET_LIST] = "cs_pvp_get_list"

SC_PVP_GET_LIST = 10902
PROTO_MAP[SC_PVP_GET_LIST] = "sc_pvp_get_list"

CS_PVP_FIGHT = 10904
PROTO_MAP[CS_PVP_FIGHT] = "cs_pvp_fight"

SC_PVP_FIGHT = 10905
PROTO_MAP[SC_PVP_FIGHT] = "sc_pvp_fight"

CS_PVP_REFRESH = 10906
PROTO_MAP[CS_PVP_REFRESH] = "cs_pvp_refresh"

SC_PVP_REFRESH = 10907
PROTO_MAP[SC_PVP_REFRESH] = "sc_pvp_refresh"

CS_PVP_TOP_LIST = 10908
PROTO_MAP[CS_PVP_TOP_LIST] = "cs_pvp_top_list"

SC_PVP_TOP_LIST = 10909
PROTO_MAP[SC_PVP_TOP_LIST] = "sc_pvp_top_list"

CS_PVP_FIGHT_BUY = 10910
PROTO_MAP[CS_PVP_FIGHT_BUY] = "cs_pvp_fight_buy"

SC_PVP_FIGHT_BUY = 10911
PROTO_MAP[SC_PVP_FIGHT_BUY] = "sc_pvp_fight_buy"

CS_PVP_COOL_ERASE = 10912
PROTO_MAP[CS_PVP_COOL_ERASE] = "cs_pvp_cool_erase"

SC_PVP_COOL_ERASE = 10913
PROTO_MAP[SC_PVP_COOL_ERASE] = "sc_pvp_cool_erase"

CS_PVP_HIST_LIST = 10915
PROTO_MAP[CS_PVP_HIST_LIST] = "cs_pvp_hist_list"

SC_PVP_HIST_LIST = 10916
PROTO_MAP[SC_PVP_HIST_LIST] = "sc_pvp_hist_list"

CS_PVP_FIGHT_REPLAY = 10917
PROTO_MAP[CS_PVP_FIGHT_REPLAY] = "cs_pvp_fight_replay"

SC_PVP_FIGHT_REPLAY = 10918
PROTO_MAP[SC_PVP_FIGHT_REPLAY] = "sc_pvp_fight_replay"

CS_PVP_RANK_REWARD = 10919
PROTO_MAP[CS_PVP_RANK_REWARD] = "cs_pvp_rank_reward"

SC_PVP_RANK_REWARD = 10920
PROTO_MAP[SC_PVP_RANK_REWARD] = "sc_pvp_rank_reward"

CS_PVP_RANK_DRAW = 10922
PROTO_MAP[CS_PVP_RANK_DRAW] = "cs_pvp_rank_draw"

SC_PVP_RANK_DRAW = 10923
PROTO_MAP[SC_PVP_RANK_DRAW] = "sc_pvp_rank_draw"

CS_PVP_ACTPOINT_REWARD = 10924
PROTO_MAP[CS_PVP_ACTPOINT_REWARD] = "cs_pvp_actpoint_reward"

SC_PVP_ACTPOINT_REWARD = 10925
PROTO_MAP[SC_PVP_ACTPOINT_REWARD] = "sc_pvp_actpoint_reward"

CS_PVP_ACTPOINT_DRAW = 10927
PROTO_MAP[CS_PVP_ACTPOINT_DRAW] = "cs_pvp_actpoint_draw"

SC_PVP_ACTPOINT_DRAW = 10928
PROTO_MAP[SC_PVP_ACTPOINT_DRAW] = "sc_pvp_actpoint_draw"

CS_PVP_ACTPOINT_ONEKEY = 10929
PROTO_MAP[CS_PVP_ACTPOINT_ONEKEY] = "cs_pvp_actpoint_onekey"

SC_PVP_ACTPOINT_ONEKEY = 10930
PROTO_MAP[SC_PVP_ACTPOINT_ONEKEY] = "sc_pvp_actpoint_onekey"

CS_PVP_WORSHIP = 10931
PROTO_MAP[CS_PVP_WORSHIP] = "cs_pvp_worship"

SC_PVP_WORSHIP = 10932
PROTO_MAP[SC_PVP_WORSHIP] = "sc_pvp_worship"

CS_PVP_ONEKEY_WORSHIP = 10933
PROTO_MAP[CS_PVP_ONEKEY_WORSHIP] = "cs_pvp_onekey_worship"

SC_PVP_ONEKEY_WORSHIP = 10934
PROTO_MAP[SC_PVP_ONEKEY_WORSHIP] = "sc_pvp_onekey_worship"

CS_PVP_SHOW_ICON = 10936
PROTO_MAP[CS_PVP_SHOW_ICON] = "cs_pvp_show_icon"

SC_PVP_SHOW_ICON = 10937
PROTO_MAP[SC_PVP_SHOW_ICON] = "sc_pvp_show_icon"

CS_TRAINER_INFO = 11001
PROTO_MAP[CS_TRAINER_INFO] = "cs_trainer_info"

SC_TRAINER_INFO = 11002
PROTO_MAP[SC_TRAINER_INFO] = "sc_trainer_info"

CS_TRAINER_UNLOCK = 11003
PROTO_MAP[CS_TRAINER_UNLOCK] = "cs_trainer_unlock"

SC_TRAINER_UNLOCK = 11004
PROTO_MAP[SC_TRAINER_UNLOCK] = "sc_trainer_unlock"

CS_TRAINER_CHOSE = 11005
PROTO_MAP[CS_TRAINER_CHOSE] = "cs_trainer_chose"

SC_TRAINER_CHOSE = 11006
PROTO_MAP[SC_TRAINER_CHOSE] = "sc_trainer_chose"

CS_BOX_INFO = 11101
PROTO_MAP[CS_BOX_INFO] = "cs_box_info"

SC_BOX_INFO = 11102
PROTO_MAP[SC_BOX_INFO] = "sc_box_info"

CS_BOX_SELECT = 11103
PROTO_MAP[CS_BOX_SELECT] = "cs_box_select"

SC_BOX_SELECT = 11104
PROTO_MAP[SC_BOX_SELECT] = "sc_box_select"

CS_BOX_OPEN_TREASUREBOX = 11106
PROTO_MAP[CS_BOX_OPEN_TREASUREBOX] = "cs_box_open_treasurebox"

SC_BOX_OPEN_TREASUREBOX = 11107
PROTO_MAP[SC_BOX_OPEN_TREASUREBOX] = "sc_box_open_treasurebox"

CS_HEGEMONY_INFO = 11201
PROTO_MAP[CS_HEGEMONY_INFO] = "cs_hegemony_info"

SC_HEGEMONY_INFO = 11202
PROTO_MAP[SC_HEGEMONY_INFO] = "sc_hegemony_info"

CS_HEGEMONY_SIGNUP_INFO = 11203
PROTO_MAP[CS_HEGEMONY_SIGNUP_INFO] = "cs_hegemony_signup_info"

SC_HEGEMONY_SIGNUP_INFO = 11204
PROTO_MAP[SC_HEGEMONY_SIGNUP_INFO] = "sc_hegemony_signup_info"

CS_HEGEMONY_BETTING_INFO = 11208
PROTO_MAP[CS_HEGEMONY_BETTING_INFO] = "cs_hegemony_betting_info"

SC_HEGEMONY_BETTING_INFO = 11209
PROTO_MAP[SC_HEGEMONY_BETTING_INFO] = "sc_hegemony_betting_info"

CS_HEGEMONY_SIGNUP_REQUEST = 11210
PROTO_MAP[CS_HEGEMONY_SIGNUP_REQUEST] = "cs_hegemony_signup_request"

SC_HEGEMONY_SIGNUP_REQUEST = 11211
PROTO_MAP[SC_HEGEMONY_SIGNUP_REQUEST] = "sc_hegemony_signup_request"

CS_HEGEMONY_GERLIST_INFO = 11212
PROTO_MAP[CS_HEGEMONY_GERLIST_INFO] = "cs_hegemony_gerlist_info"

SC_HEGEMONY_GERLIST_INFO = 11213
PROTO_MAP[SC_HEGEMONY_GERLIST_INFO] = "sc_hegemony_gerlist_info"

CS_HEGEMONY_GERLIST_ADJUST = 11214
PROTO_MAP[CS_HEGEMONY_GERLIST_ADJUST] = "cs_hegemony_gerlist_adjust"

SC_HEGEMONY_GERLIST_ADJUST = 11215
PROTO_MAP[SC_HEGEMONY_GERLIST_ADJUST] = "sc_hegemony_gerlist_adjust"

CS_HEGEMONY_BETTING_DETAIL = 11216
PROTO_MAP[CS_HEGEMONY_BETTING_DETAIL] = "cs_hegemony_betting_detail"

SC_HEGEMONY_BETTING_DETAIL = 11217
PROTO_MAP[SC_HEGEMONY_BETTING_DETAIL] = "sc_hegemony_betting_detail"

CS_HEGEMONY_BETTING_REQUEST = 11218
PROTO_MAP[CS_HEGEMONY_BETTING_REQUEST] = "cs_hegemony_betting_request"

SC_HEGEMONY_BETTING_REQUEST = 11219
PROTO_MAP[SC_HEGEMONY_BETTING_REQUEST] = "sc_hegemony_betting_request"

CS_HEGEMONY_PRELI_INFO = 11220
PROTO_MAP[CS_HEGEMONY_PRELI_INFO] = "cs_hegemony_preli_info"

SC_HEGEMONY_PRELI_INFO = 11221
PROTO_MAP[SC_HEGEMONY_PRELI_INFO] = "sc_hegemony_preli_info"

SC_HEGEMONY_PRELI_NOTIFY = 11222
PROTO_MAP[SC_HEGEMONY_PRELI_NOTIFY] = "sc_hegemony_preli_notify"

CS_HEGEMONY_FINAL_INFO = 11223
PROTO_MAP[CS_HEGEMONY_FINAL_INFO] = "cs_hegemony_final_info"

SC_HEGEMONY_FINAL_INFO = 11224
PROTO_MAP[SC_HEGEMONY_FINAL_INFO] = "sc_hegemony_final_info"

SC_HEGEMONY_FINAL_NOTIFY = 11225
PROTO_MAP[SC_HEGEMONY_FINAL_NOTIFY] = "sc_hegemony_final_notify"

CS_HEGEMONY_HIST_INFO = 11226
PROTO_MAP[CS_HEGEMONY_HIST_INFO] = "cs_hegemony_hist_info"

SC_HEGEMONY_HIST_INFO = 11227
PROTO_MAP[SC_HEGEMONY_HIST_INFO] = "sc_hegemony_hist_info"

CS_HEGEMONY_TOPS_INFO = 11228
PROTO_MAP[CS_HEGEMONY_TOPS_INFO] = "cs_hegemony_tops_info"

SC_HEGEMONY_TOPS_INFO = 11229
PROTO_MAP[SC_HEGEMONY_TOPS_INFO] = "sc_hegemony_tops_info"

CS_HEGEMONY_REPLAY_SELF = 11234
PROTO_MAP[CS_HEGEMONY_REPLAY_SELF] = "cs_hegemony_replay_self"

SC_HEGEMONY_REPLAY_SELF = 11235
PROTO_MAP[SC_HEGEMONY_REPLAY_SELF] = "sc_hegemony_replay_self"

CS_HEGEMONY_REPLAY_FINAL = 11236
PROTO_MAP[CS_HEGEMONY_REPLAY_FINAL] = "cs_hegemony_replay_final"

SC_HEGEMONY_REPLAY_FINAL = 11237
PROTO_MAP[SC_HEGEMONY_REPLAY_FINAL] = "sc_hegemony_replay_final"

CS_HEGEMONY_EXCHANGE = 11238
PROTO_MAP[CS_HEGEMONY_EXCHANGE] = "cs_hegemony_exchange"

SC_HEGEMONY_EXCHANGE = 11239
PROTO_MAP[SC_HEGEMONY_EXCHANGE] = "sc_hegemony_exchange"

SC_HEGEMONY_STATE_UPDATE = 11240
PROTO_MAP[SC_HEGEMONY_STATE_UPDATE] = "sc_hegemony_state_update"

CS_HEGEMONY_DRAW_REWARD = 11241
PROTO_MAP[CS_HEGEMONY_DRAW_REWARD] = "cs_hegemony_draw_reward"

SC_HEGEMONY_DRAW_REWARD = 11242
PROTO_MAP[SC_HEGEMONY_DRAW_REWARD] = "sc_hegemony_draw_reward"

CS_ONLINERWD_INFO = 11301
PROTO_MAP[CS_ONLINERWD_INFO] = "cs_onlinerwd_info"

SC_ONLINERWD_INFO = 11302
PROTO_MAP[SC_ONLINERWD_INFO] = "sc_onlinerwd_info"

CS_ONLINERWD_DRAW = 11303
PROTO_MAP[CS_ONLINERWD_DRAW] = "cs_onlinerwd_draw"

SC_ONLINERWD_DRAW = 11304
PROTO_MAP[SC_ONLINERWD_DRAW] = "sc_onlinerwd_draw"

CS_BATTLE_INFO = 11401
PROTO_MAP[CS_BATTLE_INFO] = "cs_battle_info"

SC_BATTLE_INFO = 11402
PROTO_MAP[SC_BATTLE_INFO] = "sc_battle_info"

CS_BATTLE_CHAPTER = 11404
PROTO_MAP[CS_BATTLE_CHAPTER] = "cs_battle_chapter"

SC_BATTLE_CHAPTER = 11405
PROTO_MAP[SC_BATTLE_CHAPTER] = "sc_battle_chapter"

SC_BATTLE_UPDATE = 11408
PROTO_MAP[SC_BATTLE_UPDATE] = "sc_battle_update"

CS_BATTLE_FIGHT_REQUEST = 11409
PROTO_MAP[CS_BATTLE_FIGHT_REQUEST] = "cs_battle_fight_request"

SC_BATTLE_FIGHT_REQUEST = 11410
PROTO_MAP[SC_BATTLE_FIGHT_REQUEST] = "sc_battle_fight_request"

CS_BATTLE_FIGHT_REPORT = 11411
PROTO_MAP[CS_BATTLE_FIGHT_REPORT] = "cs_battle_fight_report"

SC_BATTLE_FIGHT_REPORT = 11412
PROTO_MAP[SC_BATTLE_FIGHT_REPORT] = "sc_battle_fight_report"

CS_BATTLE_CHAPTER_REWARD = 11413
PROTO_MAP[CS_BATTLE_CHAPTER_REWARD] = "cs_battle_chapter_reward"

SC_BATTLE_CHAPTER_REWARD = 11414
PROTO_MAP[SC_BATTLE_CHAPTER_REWARD] = "sc_battle_chapter_reward"

CS_BATTLE_DUNGEON_REWARD = 11415
PROTO_MAP[CS_BATTLE_DUNGEON_REWARD] = "cs_battle_dungeon_reward"

SC_BATTLE_DUNGEON_REWARD = 11416
PROTO_MAP[SC_BATTLE_DUNGEON_REWARD] = "sc_battle_dungeon_reward"

CS_BATTLE_FIGHT_SWEEP = 11417
PROTO_MAP[CS_BATTLE_FIGHT_SWEEP] = "cs_battle_fight_sweep"

SC_BATTLE_FIGHT_SWEEP = 11418
PROTO_MAP[SC_BATTLE_FIGHT_SWEEP] = "sc_battle_fight_sweep"

CS_BATTLE_STORY_FIGHT = 11419
PROTO_MAP[CS_BATTLE_STORY_FIGHT] = "cs_battle_story_fight"

SC_BATTLE_STORY_FIGHT = 11420
PROTO_MAP[SC_BATTLE_STORY_FIGHT] = "sc_battle_story_fight"

CS_BATTLE_FIGHT_REQUEST2 = 11421
PROTO_MAP[CS_BATTLE_FIGHT_REQUEST2] = "cs_battle_fight_request2"

SC_BATTLE_FIGHT_REQUEST2 = 11422
PROTO_MAP[SC_BATTLE_FIGHT_REQUEST2] = "sc_battle_fight_request2"

CS_BATTLE_FIGHT_REPORT2 = 11423
PROTO_MAP[CS_BATTLE_FIGHT_REPORT2] = "cs_battle_fight_report2"

SC_BATTLE_FIGHT_REPORT2 = 11424
PROTO_MAP[SC_BATTLE_FIGHT_REPORT2] = "sc_battle_fight_report2"

CS_BATTLE_FIGHT_SWEEP2 = 11425
PROTO_MAP[CS_BATTLE_FIGHT_SWEEP2] = "cs_battle_fight_sweep2"

SC_BATTLE_FIGHT_SWEEP2 = 11426
PROTO_MAP[SC_BATTLE_FIGHT_SWEEP2] = "sc_battle_fight_sweep2"

CS_BATTLE_FIGHT_RESET = 11427
PROTO_MAP[CS_BATTLE_FIGHT_RESET] = "cs_battle_fight_reset"

SC_BATTLE_FIGHT_RESET = 11428
PROTO_MAP[SC_BATTLE_FIGHT_RESET] = "sc_battle_fight_reset"

CS_BATTLE_FIGHT_LINE2 = 11429
PROTO_MAP[CS_BATTLE_FIGHT_LINE2] = "cs_battle_fight_line2"

SC_BATTLE_FIGHT_LINE2 = 11430
PROTO_MAP[SC_BATTLE_FIGHT_LINE2] = "sc_battle_fight_line2"

CS_BATTLE_FIGHT_SET_LINE2 = 11431
PROTO_MAP[CS_BATTLE_FIGHT_SET_LINE2] = "cs_battle_fight_set_line2"

SC_BATTLE_FIGHT_SET_LINE2 = 11432
PROTO_MAP[SC_BATTLE_FIGHT_SET_LINE2] = "sc_battle_fight_set_line2"

CS_BATTLE_ACTIVITY_LIST = 11433
PROTO_MAP[CS_BATTLE_ACTIVITY_LIST] = "cs_battle_activity_list"

SC_BATTLE_ACTIVITY_LIST = 11434
PROTO_MAP[SC_BATTLE_ACTIVITY_LIST] = "sc_battle_activity_list"

CS_ITEM_BOX_OPEN = 11523
PROTO_MAP[CS_ITEM_BOX_OPEN] = "cs_item_box_open"

SC_ITEM_BOX_OPEN = 11524
PROTO_MAP[SC_ITEM_BOX_OPEN] = "sc_item_box_open"

CS_ITEM_BOX_OPEN_ONEKEY = 11527
PROTO_MAP[CS_ITEM_BOX_OPEN_ONEKEY] = "cs_item_box_open_onekey"

SC_ITEM_BOX_OPEN_ONEKEY = 11528
PROTO_MAP[SC_ITEM_BOX_OPEN_ONEKEY] = "sc_item_box_open_onekey"

CS_ITEM_CHOSEBOX_OPEN = 11529
PROTO_MAP[CS_ITEM_CHOSEBOX_OPEN] = "cs_item_chosebox_open"

SC_ITEM_CHOSEBOX_OPEN = 11530
PROTO_MAP[SC_ITEM_CHOSEBOX_OPEN] = "sc_item_chosebox_open"

CS_ITEM_CHOSEBOX_VIEW = 11531
PROTO_MAP[CS_ITEM_CHOSEBOX_VIEW] = "cs_item_chosebox_view"

SC_ITEM_CHOSEBOX_VIEW = 11532
PROTO_MAP[SC_ITEM_CHOSEBOX_VIEW] = "sc_item_chosebox_view"

CS_ITEM_USE = 11534
PROTO_MAP[CS_ITEM_USE] = "cs_item_use"

SC_ITEM_USE = 11535
PROTO_MAP[SC_ITEM_USE] = "sc_item_use"

CS_GHANDRWD_LOGIN_INFO = 11607
PROTO_MAP[CS_GHANDRWD_LOGIN_INFO] = "cs_ghandrwd_login_info"

SC_GHANDRWD_LOGIN_INFO = 11608
PROTO_MAP[SC_GHANDRWD_LOGIN_INFO] = "sc_ghandrwd_login_info"

CS_GHANDRWD_LOGIN_DRAW = 11609
PROTO_MAP[CS_GHANDRWD_LOGIN_DRAW] = "cs_ghandrwd_login_draw"

SC_GHANDRWD_LOGIN_DRAW = 11610
PROTO_MAP[SC_GHANDRWD_LOGIN_DRAW] = "sc_ghandrwd_login_draw"

SC_GHANDRWD_LOGIN_UPDATE = 11611
PROTO_MAP[SC_GHANDRWD_LOGIN_UPDATE] = "sc_ghandrwd_login_update"

CS_TASK_TRUNK = 11701
PROTO_MAP[CS_TASK_TRUNK] = "cs_task_trunk"

SC_TASK_TRUNK = 11702
PROTO_MAP[SC_TASK_TRUNK] = "sc_task_trunk"

CS_TASK_DAILY = 11703
PROTO_MAP[CS_TASK_DAILY] = "cs_task_daily"

SC_TASK_DAILY = 11704
PROTO_MAP[SC_TASK_DAILY] = "sc_task_daily"

SC_TASK_NOTIFY = 11706
PROTO_MAP[SC_TASK_NOTIFY] = "sc_task_notify"

CS_TASK_DRAW = 11707
PROTO_MAP[CS_TASK_DRAW] = "cs_task_draw"

SC_TASK_DRAW = 11708
PROTO_MAP[SC_TASK_DRAW] = "sc_task_draw"

CS_TASK_ONE_DRAW = 11709
PROTO_MAP[CS_TASK_ONE_DRAW] = "cs_task_one_draw"

SC_TASK_ONE_DRAW = 11710
PROTO_MAP[SC_TASK_ONE_DRAW] = "sc_task_one_draw"

CS_ACTIVITY_PREVIEW = 11901
PROTO_MAP[CS_ACTIVITY_PREVIEW] = "cs_activity_preview"

SC_ACTIVITY_PREVIEW = 11902
PROTO_MAP[SC_ACTIVITY_PREVIEW] = "sc_activity_preview"

SC_ACTIVITY_NOTIFY = 11904
PROTO_MAP[SC_ACTIVITY_NOTIFY] = "sc_activity_notify"

CS_ACTIVITY_INFO = 11905
PROTO_MAP[CS_ACTIVITY_INFO] = "cs_activity_info"

SC_ACTIVITY_INFO = 11906
PROTO_MAP[SC_ACTIVITY_INFO] = "sc_activity_info"

CS_ACTIVITY_DRAW = 11910
PROTO_MAP[CS_ACTIVITY_DRAW] = "cs_activity_draw"

SC_ACTIVITY_DRAW = 11911
PROTO_MAP[SC_ACTIVITY_DRAW] = "sc_activity_draw"

CS_ACTIVITY_CZJJ_BUY = 11912
PROTO_MAP[CS_ACTIVITY_CZJJ_BUY] = "cs_activity_czjj_buy"

SC_ACTIVITY_CZJJ_BUY = 11913
PROTO_MAP[SC_ACTIVITY_CZJJ_BUY] = "sc_activity_czjj_buy"

CS_ACTIVITY_ACTIVE_VIEW = 11914
PROTO_MAP[CS_ACTIVITY_ACTIVE_VIEW] = "cs_activity_active_view"

SC_ACTIVITY_ACTIVY_VIEW = 11915
PROTO_MAP[SC_ACTIVITY_ACTIVY_VIEW] = "sc_activity_activy_view"

CS_ACTIVITY_KAIFU = 11918
PROTO_MAP[CS_ACTIVITY_KAIFU] = "cs_activity_kaifu"

SC_ACITIVITY_KAIFU = 11920
PROTO_MAP[SC_ACITIVITY_KAIFU] = "sc_acitivity_kaifu"

CS_ACTIVITY_KAIFU_DRAW = 11921
PROTO_MAP[CS_ACTIVITY_KAIFU_DRAW] = "cs_activity_kaifu_draw"

SC_ACTIVITY_KAIFU_DRAW = 11922
PROTO_MAP[SC_ACTIVITY_KAIFU_DRAW] = "sc_activity_kaifu_draw"

CS_ACTIVITY_KAIFU_DRAWEND = 11923
PROTO_MAP[CS_ACTIVITY_KAIFU_DRAWEND] = "cs_activity_kaifu_drawend"

SC_ACTIVITY_KAIFU_DRAWEND = 11924
PROTO_MAP[SC_ACTIVITY_KAIFU_DRAWEND] = "sc_activity_kaifu_drawend"

CS_VIP_INFO = 12001
PROTO_MAP[CS_VIP_INFO] = "cs_vip_info"

SC_VIP_INFO = 12002
PROTO_MAP[SC_VIP_INFO] = "sc_vip_info"

SC_VIP_UPDATE = 12004
PROTO_MAP[SC_VIP_UPDATE] = "sc_vip_update"

CS_VIP_GIFT = 12005
PROTO_MAP[CS_VIP_GIFT] = "cs_vip_gift"

SC_VIP_GIFT = 12006
PROTO_MAP[SC_VIP_GIFT] = "sc_vip_gift"

CS_VIP_ITEM_EFFECT = 12007
PROTO_MAP[CS_VIP_ITEM_EFFECT] = "cs_vip_item_effect"

SC_VIP_ITEM_EFFECT = 12008
PROTO_MAP[SC_VIP_ITEM_EFFECT] = "sc_vip_item_effect"

CS_FAMILY_INFO = 12104
PROTO_MAP[CS_FAMILY_INFO] = "cs_family_info"

SC_FAMILY_INFO = 12105
PROTO_MAP[SC_FAMILY_INFO] = "sc_family_info"

CS_FAMILY_LIST = 12106
PROTO_MAP[CS_FAMILY_LIST] = "cs_family_list"

SC_FAMILY_LIST = 12107
PROTO_MAP[SC_FAMILY_LIST] = "sc_family_list"

CS_FAMILY_CREATE = 12108
PROTO_MAP[CS_FAMILY_CREATE] = "cs_family_create"

SC_FAMILY_CREATE = 12109
PROTO_MAP[SC_FAMILY_CREATE] = "sc_family_create"

CS_FAMILY_SEND_APPLY = 12110
PROTO_MAP[CS_FAMILY_SEND_APPLY] = "cs_family_send_apply"

SC_FAMILY_SEND_APPLY = 12111
PROTO_MAP[SC_FAMILY_SEND_APPLY] = "sc_family_send_apply"

SC_FAMILY_APPLY_NOTIFY = 12112
PROTO_MAP[SC_FAMILY_APPLY_NOTIFY] = "sc_family_apply_notify"

CS_FAMILY_APPLY_LIST = 12114
PROTO_MAP[CS_FAMILY_APPLY_LIST] = "cs_family_apply_list"

SC_FAMILY_APPLY_LIST = 12115
PROTO_MAP[SC_FAMILY_APPLY_LIST] = "sc_family_apply_list"

CS_FAMILY_HANDLE_APPLY = 12116
PROTO_MAP[CS_FAMILY_HANDLE_APPLY] = "cs_family_handle_apply"

SC_FAMILY_HANDLE_APPLY = 12117
PROTO_MAP[SC_FAMILY_HANDLE_APPLY] = "sc_family_handle_apply"

CS_FAMILY_CANCEL_APPLY = 12118
PROTO_MAP[CS_FAMILY_CANCEL_APPLY] = "cs_family_cancel_apply"

SC_FAMILY_CANCEL_APPLY = 12119
PROTO_MAP[SC_FAMILY_CANCEL_APPLY] = "sc_family_cancel_apply"

SC_FAMILY_CANCEL_NOTIFY = 12120
PROTO_MAP[SC_FAMILY_CANCEL_NOTIFY] = "sc_family_cancel_notify"

SC_FAMILY_HANDLE_NOTIFY = 12121
PROTO_MAP[SC_FAMILY_HANDLE_NOTIFY] = "sc_family_handle_notify"

CS_FAMILY_SEARCH = 12122
PROTO_MAP[CS_FAMILY_SEARCH] = "cs_family_search"

SC_FAMILY_SEARCH = 12123
PROTO_MAP[SC_FAMILY_SEARCH] = "sc_family_search"

CS_FAMILY_KICK = 12124
PROTO_MAP[CS_FAMILY_KICK] = "cs_family_kick"

SC_FAMILY_KICK = 12125
PROTO_MAP[SC_FAMILY_KICK] = "sc_family_kick"

CS_FAMILY_QUIT = 12126
PROTO_MAP[CS_FAMILY_QUIT] = "cs_family_quit"

SC_FAMILY_QUIT = 12127
PROTO_MAP[SC_FAMILY_QUIT] = "sc_family_quit"

SC_FAMILY_UPDATE_NOTIFY = 12128
PROTO_MAP[SC_FAMILY_UPDATE_NOTIFY] = "sc_family_update_notify"

SC_FMEMBER_NEW_NOTIFY = 12129
PROTO_MAP[SC_FMEMBER_NEW_NOTIFY] = "sc_fmember_new_notify"

SC_FMEMBER_DEL_NOTIFY = 12130
PROTO_MAP[SC_FMEMBER_DEL_NOTIFY] = "sc_fmember_del_notify"

CS_FAMILY_MANAGE = 12131
PROTO_MAP[CS_FAMILY_MANAGE] = "cs_family_manage"

SC_FAMILY_MANAGE = 12132
PROTO_MAP[SC_FAMILY_MANAGE] = "sc_family_manage"

CS_FAMILY_DISSOLVE = 12133
PROTO_MAP[CS_FAMILY_DISSOLVE] = "cs_family_dissolve"

SC_FAMILY_DISSOLVE = 12134
PROTO_MAP[SC_FAMILY_DISSOLVE] = "sc_family_dissolve"

SC_FAMILY_MANAGE_NOTIFY = 12135
PROTO_MAP[SC_FAMILY_MANAGE_NOTIFY] = "sc_family_manage_notify"

SC_FAMILY_DISSOLVE_NOTIFY = 12136
PROTO_MAP[SC_FAMILY_DISSOLVE_NOTIFY] = "sc_family_dissolve_notify"

CS_FAMILY_DONATE = 12137
PROTO_MAP[CS_FAMILY_DONATE] = "cs_family_donate"

SC_FAMILY_DONATE = 12138
PROTO_MAP[SC_FAMILY_DONATE] = "sc_family_donate"

CS_FAMILY_EDIT = 12139
PROTO_MAP[CS_FAMILY_EDIT] = "cs_family_edit"

SC_FAMILY_EDIT = 12140
PROTO_MAP[SC_FAMILY_EDIT] = "sc_family_edit"

SC_FAMILY_JOIN_NOTIFY = 12141
PROTO_MAP[SC_FAMILY_JOIN_NOTIFY] = "sc_family_join_notify"

SC_FAMILY_AGREED_NOTIFY = 12142
PROTO_MAP[SC_FAMILY_AGREED_NOTIFY] = "sc_family_agreed_notify"

SC_FMEMBER_STATE_TRANS_NOTIFY = 12143
PROTO_MAP[SC_FMEMBER_STATE_TRANS_NOTIFY] = "sc_fmember_state_trans_notify"

SC_FAMILY_REFUSED_NOTIFY = 12144
PROTO_MAP[SC_FAMILY_REFUSED_NOTIFY] = "sc_family_refused_notify"

SC_FAMILY_CONS_NOTIFY = 12146
PROTO_MAP[SC_FAMILY_CONS_NOTIFY] = "sc_family_cons_notify"

CS_FAMILY_UPGRADE_TECHLV = 12147
PROTO_MAP[CS_FAMILY_UPGRADE_TECHLV] = "cs_family_upgrade_techlv"

SC_FAMILY_UPGRADE_TECHLV = 12148
PROTO_MAP[SC_FAMILY_UPGRADE_TECHLV] = "sc_family_upgrade_techlv"

SC_FAMILY_TECH_NOTIFY = 12149
PROTO_MAP[SC_FAMILY_TECH_NOTIFY] = "sc_family_tech_notify"

SC_FAMILY_LOG_NOTIFY = 12151
PROTO_MAP[SC_FAMILY_LOG_NOTIFY] = "sc_family_log_notify"

CS_FAMILY_MSG_LIST = 12153
PROTO_MAP[CS_FAMILY_MSG_LIST] = "cs_family_msg_list"

SC_FAMILY_MSG_LIST = 12154
PROTO_MAP[SC_FAMILY_MSG_LIST] = "sc_family_msg_list"

SC_FAMILY_MSG_NOTIFY = 12155
PROTO_MAP[SC_FAMILY_MSG_NOTIFY] = "sc_family_msg_notify"

CS_FAMILY_SEND_MSG = 12156
PROTO_MAP[CS_FAMILY_SEND_MSG] = "cs_family_send_msg"

SC_FAMILY_SEND_MSG = 12157
PROTO_MAP[SC_FAMILY_SEND_MSG] = "sc_family_send_msg"

SC_FAMILY_KICKED_NOTIFY = 12158
PROTO_MAP[SC_FAMILY_KICKED_NOTIFY] = "sc_family_kicked_notify"

SC_FMEMBER_UPDATE_NOTIFY = 12159
PROTO_MAP[SC_FMEMBER_UPDATE_NOTIFY] = "sc_fmember_update_notify"

SC_FAMILY_EDIT_NOTIFY = 12160
PROTO_MAP[SC_FAMILY_EDIT_NOTIFY] = "sc_family_edit_notify"

SC_FAMILY_ACTIVEPOINTS_NOTIFY = 12161
PROTO_MAP[SC_FAMILY_ACTIVEPOINTS_NOTIFY] = "sc_family_activepoints_notify"

CS_FAMILY_SEND_APPLY_FAST = 12162
PROTO_MAP[CS_FAMILY_SEND_APPLY_FAST] = "cs_family_send_apply_fast"

CS_FAMILY_IMPEACH_INFO = 12163
PROTO_MAP[CS_FAMILY_IMPEACH_INFO] = "cs_family_impeach_info"

SC_FAMILY_IMPEACH_INFO = 12164
PROTO_MAP[SC_FAMILY_IMPEACH_INFO] = "sc_family_impeach_info"

CS_FAMILY_IMPEACH_START = 12165
PROTO_MAP[CS_FAMILY_IMPEACH_START] = "cs_family_impeach_start"

SC_FAMILY_IMPEACH_START = 12166
PROTO_MAP[SC_FAMILY_IMPEACH_START] = "sc_family_impeach_start"

CS_FAMILY_IMPEACH_VOTE = 12167
PROTO_MAP[CS_FAMILY_IMPEACH_VOTE] = "cs_family_impeach_vote"

SC_FAMILY_IMPEACH_VOTE = 12168
PROTO_MAP[SC_FAMILY_IMPEACH_VOTE] = "sc_family_impeach_vote"

SC_FAMILY_IMPEACH_NOTIFY = 12169
PROTO_MAP[SC_FAMILY_IMPEACH_NOTIFY] = "sc_family_impeach_notify"

SC_FAMILY_IMPEACH_SUCCESS = 12170
PROTO_MAP[SC_FAMILY_IMPEACH_SUCCESS] = "sc_family_impeach_success"

CS_FAMILY_PACKET_INFO = 12174
PROTO_MAP[CS_FAMILY_PACKET_INFO] = "cs_family_packet_info"

CS_FAMILY_PACKET_DRAWFAMILY = 12175
PROTO_MAP[CS_FAMILY_PACKET_DRAWFAMILY] = "cs_family_packet_drawfamily"

SC_FAMILY_PACKET_DRAWFAMILY = 12176
PROTO_MAP[SC_FAMILY_PACKET_DRAWFAMILY] = "sc_family_packet_drawfamily"

CS_FAMILY_SENDPACKET = 12177
PROTO_MAP[CS_FAMILY_SENDPACKET] = "cs_family_sendpacket"

SC_FAMILY_SENDPACKET = 12178
PROTO_MAP[SC_FAMILY_SENDPACKET] = "sc_family_sendpacket"

CS_FAMILY_PACKET_DRAWROLE = 12179
PROTO_MAP[CS_FAMILY_PACKET_DRAWROLE] = "cs_family_packet_drawrole"

SC_FAMILY_PACKET_DRAWROLE = 12180
PROTO_MAP[SC_FAMILY_PACKET_DRAWROLE] = "sc_family_packet_drawrole"

CS_FAMILY_PACKET_RANKLIST = 12181
PROTO_MAP[CS_FAMILY_PACKET_RANKLIST] = "cs_family_packet_ranklist"

SC_FAMILY_PACKET_RANKLIST = 12182
PROTO_MAP[SC_FAMILY_PACKET_RANKLIST] = "sc_family_packet_ranklist"

SC_FAMILY_PACKET_NOTIFY = 12184
PROTO_MAP[SC_FAMILY_PACKET_NOTIFY] = "sc_family_packet_notify"

SC_FAMILY_PACKET_INFO = 12185
PROTO_MAP[SC_FAMILY_PACKET_INFO] = "sc_family_packet_info"

CS_FAMILY_SETARG = 12187
PROTO_MAP[CS_FAMILY_SETARG] = "cs_family_setarg"

SC_FAMILY_SETARG = 12188
PROTO_MAP[SC_FAMILY_SETARG] = "sc_family_setarg"

CS_FAMILY_QUICK_JOIN = 12189
PROTO_MAP[CS_FAMILY_QUICK_JOIN] = "cs_family_quick_join"

SC_FAMILY_QUICK_JOIN = 12190
PROTO_MAP[SC_FAMILY_QUICK_JOIN] = "sc_family_quick_join"

CS_FAMILY_RECRUIT = 12191
PROTO_MAP[CS_FAMILY_RECRUIT] = "cs_family_recruit"

SC_FAMILY_RECRUIT = 12192
PROTO_MAP[SC_FAMILY_RECRUIT] = "sc_family_recruit"

CS_FAMILY_VIEW_OTHER = 12193
PROTO_MAP[CS_FAMILY_VIEW_OTHER] = "cs_family_view_other"

SC_FAMILY_VIEW_OTHER = 12194
PROTO_MAP[SC_FAMILY_VIEW_OTHER] = "sc_family_view_other"

CS_FAMILY_SEND_MEMBER_MAIL = 12195
PROTO_MAP[CS_FAMILY_SEND_MEMBER_MAIL] = "cs_family_send_member_mail"

SC_FAMILY_SEND_MEMBER_MAIL = 12196
PROTO_MAP[SC_FAMILY_SEND_MEMBER_MAIL] = "sc_family_send_member_mail"

CS_FBOSS_INFO = 12201
PROTO_MAP[CS_FBOSS_INFO] = "cs_fboss_info"

SC_FBOSS_INFO = 12202
PROTO_MAP[SC_FBOSS_INFO] = "sc_fboss_info"

CS_FBOSS_DUNGEON_DETIAL = 12203
PROTO_MAP[CS_FBOSS_DUNGEON_DETIAL] = "cs_fboss_dungeon_detial"

SC_FBOSS_DUNGEON_DETIAL = 12204
PROTO_MAP[SC_FBOSS_DUNGEON_DETIAL] = "sc_fboss_dungeon_detial"

CS_FBOSS_RANK = 12206
PROTO_MAP[CS_FBOSS_RANK] = "cs_fboss_rank"

SC_FBOSS_RANK = 12207
PROTO_MAP[SC_FBOSS_RANK] = "sc_fboss_rank"

CS_FBOSS_PASSRANK = 12209
PROTO_MAP[CS_FBOSS_PASSRANK] = "cs_fboss_passrank"

SC_FBOSS_PASSRANK = 12210
PROTO_MAP[SC_FBOSS_PASSRANK] = "sc_fboss_passrank"

CS_FBOSS_ATK = 12212
PROTO_MAP[CS_FBOSS_ATK] = "cs_fboss_atk"

SC_FBOSS_ATK = 12213
PROTO_MAP[SC_FBOSS_ATK] = "sc_fboss_atk"

CS_FBOSS_DRAW = 12214
PROTO_MAP[CS_FBOSS_DRAW] = "cs_fboss_draw"

SC_FBOSS_DRAW = 12215
PROTO_MAP[SC_FBOSS_DRAW] = "sc_fboss_draw"

CS_FBOSS_SETLINE = 12216
PROTO_MAP[CS_FBOSS_SETLINE] = "cs_fboss_setline"

SC_FBOSS_SETLINE = 12217
PROTO_MAP[SC_FBOSS_SETLINE] = "sc_fboss_setline"

CS_FBOSS_REPORT = 12218
PROTO_MAP[CS_FBOSS_REPORT] = "cs_fboss_report"

SC_FBOSS_REPORT = 12219
PROTO_MAP[SC_FBOSS_REPORT] = "sc_fboss_report"

SC_FBOSS_SYNC = 12220
PROTO_MAP[SC_FBOSS_SYNC] = "sc_fboss_sync"

CS_FFIGHT_PREVIEW = 12301
PROTO_MAP[CS_FFIGHT_PREVIEW] = "cs_ffight_preview"

SC_FFIGHT_PREVIEW = 12302
PROTO_MAP[SC_FFIGHT_PREVIEW] = "sc_ffight_preview"

CS_FFIGHT_DETAIL = 12303
PROTO_MAP[CS_FFIGHT_DETAIL] = "cs_ffight_detail"

SC_FFIGHT_DETAIL = 12304
PROTO_MAP[SC_FFIGHT_DETAIL] = "sc_ffight_detail"

CS_FFIGHT_HIST_WITH_REPLAY = 12308
PROTO_MAP[CS_FFIGHT_HIST_WITH_REPLAY] = "cs_ffight_hist_with_replay"

SC_FFIGHT_HIST_WITH_REPLAY = 12309
PROTO_MAP[SC_FFIGHT_HIST_WITH_REPLAY] = "sc_ffight_hist_with_replay"

SC_FFIGHT_MEMBER_UPDATE = 12310
PROTO_MAP[SC_FFIGHT_MEMBER_UPDATE] = "sc_ffight_member_update"

CS_FFIGHT_SIGNUP = 12311
PROTO_MAP[CS_FFIGHT_SIGNUP] = "cs_ffight_signup"

SC_FFIGHT_SIGNUP = 12312
PROTO_MAP[SC_FFIGHT_SIGNUP] = "sc_ffight_signup"

CS_FFIGHT_ATTACK = 12313
PROTO_MAP[CS_FFIGHT_ATTACK] = "cs_ffight_attack"

SC_FFIGHT_ATTACK = 12314
PROTO_MAP[SC_FFIGHT_ATTACK] = "sc_ffight_attack"

CS_FFIGHT_PREV_HIST_LIST = 12315
PROTO_MAP[CS_FFIGHT_PREV_HIST_LIST] = "cs_ffight_prev_hist_list"

SC_FFIGHT_PREV_HIST_LIST = 12316
PROTO_MAP[SC_FFIGHT_PREV_HIST_LIST] = "sc_ffight_prev_hist_list"

CS_FFIGHT_TOPS = 12317
PROTO_MAP[CS_FFIGHT_TOPS] = "cs_ffight_tops"

SC_FFIGHT_TOPS = 12318
PROTO_MAP[SC_FFIGHT_TOPS] = "sc_ffight_tops"

CS_PAY_INFO = 12401
PROTO_MAP[CS_PAY_INFO] = "cs_pay_info"

SC_PAY_INFO = 12402
PROTO_MAP[SC_PAY_INFO] = "sc_pay_info"

CS_PAY_TEST = 12403
PROTO_MAP[CS_PAY_TEST] = "cs_pay_test"

SC_PAY_NOTIFY = 12404
PROTO_MAP[SC_PAY_NOTIFY] = "sc_pay_notify"

CS_PAY_FIRST_DRAW = 12405
PROTO_MAP[CS_PAY_FIRST_DRAW] = "cs_pay_first_draw"

SC_PAY_FIRST_DRAW = 12406
PROTO_MAP[SC_PAY_FIRST_DRAW] = "sc_pay_first_draw"

CS_PAY_OFFLINE_ENSURE = 12407
PROTO_MAP[CS_PAY_OFFLINE_ENSURE] = "cs_pay_offline_ensure"

CS_TALK_MSG_LIST = 12502
PROTO_MAP[CS_TALK_MSG_LIST] = "cs_talk_msg_list"

SC_TALK_MSG_LIST = 12503
PROTO_MAP[SC_TALK_MSG_LIST] = "sc_talk_msg_list"

SC_TALK_MSG_NOTIFY = 12504
PROTO_MAP[SC_TALK_MSG_NOTIFY] = "sc_talk_msg_notify"

CS_TALK_SEND_MSG = 12505
PROTO_MAP[CS_TALK_SEND_MSG] = "cs_talk_send_msg"

SC_TALK_SEND_MSG = 12506
PROTO_MAP[SC_TALK_SEND_MSG] = "sc_talk_send_msg"

CS_TALK_SET_SHIELD = 12507
PROTO_MAP[CS_TALK_SET_SHIELD] = "cs_talk_set_shield"

SC_TALK_SET_SHIELD = 12508
PROTO_MAP[SC_TALK_SET_SHIELD] = "sc_talk_set_shield"

CS_FBIRD_INFO = 12601
PROTO_MAP[CS_FBIRD_INFO] = "cs_fbird_info"

SC_FBIRD_INFO = 12602
PROTO_MAP[SC_FBIRD_INFO] = "sc_fbird_info"

CS_FBIRD_RANK = 12603
PROTO_MAP[CS_FBIRD_RANK] = "cs_fbird_rank"

SC_FBIRD_RANK = 12604
PROTO_MAP[SC_FBIRD_RANK] = "sc_fbird_rank"

CS_FBIRD_DRAW = 12606
PROTO_MAP[CS_FBIRD_DRAW] = "cs_fbird_draw"

SC_FBIRD_DRAW = 12607
PROTO_MAP[SC_FBIRD_DRAW] = "sc_fbird_draw"

CS_FSCHOOL_INFO = 12701
PROTO_MAP[CS_FSCHOOL_INFO] = "cs_fschool_info"

SC_FSCHOOL_INFO = 12702
PROTO_MAP[SC_FSCHOOL_INFO] = "sc_fschool_info"

CS_FSCHOOL_SETGER = 12705
PROTO_MAP[CS_FSCHOOL_SETGER] = "cs_fschool_setger"

SC_FSCHOOL_SETGER = 12706
PROTO_MAP[SC_FSCHOOL_SETGER] = "sc_fschool_setger"

CS_FSCHOOL_VIEWOTHER = 12707
PROTO_MAP[CS_FSCHOOL_VIEWOTHER] = "cs_fschool_viewother"

SC_FSCHOOL_VIEWOTHER = 12708
PROTO_MAP[SC_FSCHOOL_VIEWOTHER] = "sc_fschool_viewother"

CS_FSCHOOL_ACCELERATE = 12709
PROTO_MAP[CS_FSCHOOL_ACCELERATE] = "cs_fschool_accelerate"

SC_FSCHOOL_ACCELERATE = 12710
PROTO_MAP[SC_FSCHOOL_ACCELERATE] = "sc_fschool_accelerate"

CS_FSCHOOL_ACCELERATE_AUTO = 12711
PROTO_MAP[CS_FSCHOOL_ACCELERATE_AUTO] = "cs_fschool_accelerate_auto"

SC_FSCHOOL_ACCELERATE_AUTO = 12712
PROTO_MAP[SC_FSCHOOL_ACCELERATE_AUTO] = "sc_fschool_accelerate_auto"

CS_GUIDE_LIST = 12801
PROTO_MAP[CS_GUIDE_LIST] = "cs_guide_list"

SC_GUIDE_LIST = 12802
PROTO_MAP[SC_GUIDE_LIST] = "sc_guide_list"

SC_GUIDE_NOTIFY = 12804
PROTO_MAP[SC_GUIDE_NOTIFY] = "sc_guide_notify"

CS_GUIDE_DRAW = 12805
PROTO_MAP[CS_GUIDE_DRAW] = "cs_guide_draw"

SC_GUIDE_DRAW = 12806
PROTO_MAP[SC_GUIDE_DRAW] = "sc_guide_draw"

CS_ACHIEVE_FOSTER = 12901
PROTO_MAP[CS_ACHIEVE_FOSTER] = "cs_achieve_foster"

SC_ACHIEVE_FOSTER = 12902
PROTO_MAP[SC_ACHIEVE_FOSTER] = "sc_achieve_foster"

CS_ACHIEVE_ADVENTURE = 12903
PROTO_MAP[CS_ACHIEVE_ADVENTURE] = "cs_achieve_adventure"

SC_ACHIEVE_ADVENTURE = 12904
PROTO_MAP[SC_ACHIEVE_ADVENTURE] = "sc_achieve_adventure"

CS_ACHIEVE_ACTIVITY = 12905
PROTO_MAP[CS_ACHIEVE_ACTIVITY] = "cs_achieve_activity"

SC_ACHIEVE_ACTIVITY = 12906
PROTO_MAP[SC_ACHIEVE_ACTIVITY] = "sc_achieve_activity"

SC_ACHIEVE_NOTIFY = 12908
PROTO_MAP[SC_ACHIEVE_NOTIFY] = "sc_achieve_notify"

CS_ACHIEVE_DRAW = 12909
PROTO_MAP[CS_ACHIEVE_DRAW] = "cs_achieve_draw"

SC_ACHIEVE_DRAW = 12910
PROTO_MAP[SC_ACHIEVE_DRAW] = "sc_achieve_draw"

CS_ACHIEVE_ONE_DRAW = 12911
PROTO_MAP[CS_ACHIEVE_ONE_DRAW] = "cs_achieve_one_draw"

SC_ACHIEVE_ONE_DRAW = 12912
PROTO_MAP[SC_ACHIEVE_ONE_DRAW] = "sc_achieve_one_draw"

SC_ACITIVITY_KAIFU_NOTIFY = 12925
PROTO_MAP[SC_ACITIVITY_KAIFU_NOTIFY] = "sc_acitivity_kaifu_notify"

CS_POKDEX_INFO = 13001
PROTO_MAP[CS_POKDEX_INFO] = "cs_pokdex_info"

SC_POKDEX_INFO = 13002
PROTO_MAP[SC_POKDEX_INFO] = "sc_pokdex_info"

CS_POKDEX_FEED = 13004
PROTO_MAP[CS_POKDEX_FEED] = "cs_pokdex_feed"

SC_POKDEX_FEED = 13005
PROTO_MAP[SC_POKDEX_FEED] = "sc_pokdex_feed"

CS_POKDEX_ONEKEY_FEED = 13006
PROTO_MAP[CS_POKDEX_ONEKEY_FEED] = "cs_pokdex_onekey_feed"

SC_POKDEX_ONEKEY_FEED = 13007
PROTO_MAP[SC_POKDEX_ONEKEY_FEED] = "sc_pokdex_onekey_feed"

CS_POKDEX_UPRANK = 13008
PROTO_MAP[CS_POKDEX_UPRANK] = "cs_pokdex_uprank"

SC_POKDEX_UPRANK = 13009
PROTO_MAP[SC_POKDEX_UPRANK] = "sc_pokdex_uprank"

SC_POKDEX_NOTIFY = 13010
PROTO_MAP[SC_POKDEX_NOTIFY] = "sc_pokdex_notify"

CS_TRIAL_INFO = 13101
PROTO_MAP[CS_TRIAL_INFO] = "cs_trial_info"

SC_TRIAL_INFO1 = 13102
PROTO_MAP[SC_TRIAL_INFO1] = "sc_trial_info1"

SC_TRIAL_INFO2 = 13103
PROTO_MAP[SC_TRIAL_INFO2] = "sc_trial_info2"

SC_TRIAL_UPDATE = 13105
PROTO_MAP[SC_TRIAL_UPDATE] = "sc_trial_update"

CS_TRIAL_JUMP = 13106
PROTO_MAP[CS_TRIAL_JUMP] = "cs_trial_jump"

SC_TRIAL_JUMP = 13107
PROTO_MAP[SC_TRIAL_JUMP] = "sc_trial_jump"

CS_TRIAL_CHALLENGE = 13108
PROTO_MAP[CS_TRIAL_CHALLENGE] = "cs_trial_challenge"

SC_TRIAL_CHALLENGE = 13109
PROTO_MAP[SC_TRIAL_CHALLENGE] = "sc_trial_challenge"

CS_TRIAL_CHALLENGE_BACK = 13110
PROTO_MAP[CS_TRIAL_CHALLENGE_BACK] = "cs_trial_challenge_back"

SC_TRIAL_CHALLENGE_BACK = 13111
PROTO_MAP[SC_TRIAL_CHALLENGE_BACK] = "sc_trial_challenge_back"

CS_TRIAL_BUFF_BUY = 13112
PROTO_MAP[CS_TRIAL_BUFF_BUY] = "cs_trial_buff_buy"

SC_TRIAL_BUFF_BUY = 13113
PROTO_MAP[SC_TRIAL_BUFF_BUY] = "sc_trial_buff_buy"

CS_TRIAL_TBOX_OPEN = 13115
PROTO_MAP[CS_TRIAL_TBOX_OPEN] = "cs_trial_tbox_open"

SC_TRIAL_TBOX_OPEN = 13116
PROTO_MAP[SC_TRIAL_TBOX_OPEN] = "sc_trial_tbox_open"

CS_TRIAL_NEXT_LV = 13117
PROTO_MAP[CS_TRIAL_NEXT_LV] = "cs_trial_next_lv"

SC_TRIAL_NEXT_LV = 13118
PROTO_MAP[SC_TRIAL_NEXT_LV] = "sc_trial_next_lv"

CS_TRIAL_SCORE_RANK = 13119
PROTO_MAP[CS_TRIAL_SCORE_RANK] = "cs_trial_score_rank"

SC_TRIAL_SCORE_RANK = 13120
PROTO_MAP[SC_TRIAL_SCORE_RANK] = "sc_trial_score_rank"

CS_TRIAL_HSR_INFO = 13122
PROTO_MAP[CS_TRIAL_HSR_INFO] = "cs_trial_hsr_info"

SC_TRIAL_HSR_INFO = 13123
PROTO_MAP[SC_TRIAL_HSR_INFO] = "sc_trial_hsr_info"

SC_TRIAL_HSR_UPDATE = 13125
PROTO_MAP[SC_TRIAL_HSR_UPDATE] = "sc_trial_hsr_update"

CS_TRIAL_HSR_DRAW = 13126
PROTO_MAP[CS_TRIAL_HSR_DRAW] = "cs_trial_hsr_draw"

SC_TRIAL_HSR_DRAW = 13127
PROTO_MAP[SC_TRIAL_HSR_DRAW] = "sc_trial_hsr_draw"

CS_TRIAL_FJ_LEAVE = 13129
PROTO_MAP[CS_TRIAL_FJ_LEAVE] = "cs_trial_fj_leave"

SC_TRIAL_FJ_LEAVE = 13130
PROTO_MAP[SC_TRIAL_FJ_LEAVE] = "sc_trial_fj_leave"

CS_TRIAL_TBOX_FIXREWARD = 13133
PROTO_MAP[CS_TRIAL_TBOX_FIXREWARD] = "cs_trial_tbox_fixreward"

SC_TRIAL_TBOX_FIXREWARD = 13134
PROTO_MAP[SC_TRIAL_TBOX_FIXREWARD] = "sc_trial_tbox_fixreward"

SC_TRIAL_CURFEW = 13135
PROTO_MAP[SC_TRIAL_CURFEW] = "sc_trial_curfew"

CS_FTIGER_INFO = 13201
PROTO_MAP[CS_FTIGER_INFO] = "cs_ftiger_info"

SC_FTIGER_INFO = 13202
PROTO_MAP[SC_FTIGER_INFO] = "sc_ftiger_info"

CS_FTIGER_RANK = 13204
PROTO_MAP[CS_FTIGER_RANK] = "cs_ftiger_rank"

SC_FTIGER_RANK = 13205
PROTO_MAP[SC_FTIGER_RANK] = "sc_ftiger_rank"

CS_FTIGER_PLAY = 13207
PROTO_MAP[CS_FTIGER_PLAY] = "cs_ftiger_play"

SC_FTIGER_PLAY = 13208
PROTO_MAP[SC_FTIGER_PLAY] = "sc_ftiger_play"

CS_FTIGER_REFRESH = 13209
PROTO_MAP[CS_FTIGER_REFRESH] = "cs_ftiger_refresh"

SC_FTIGER_REFRESH = 13210
PROTO_MAP[SC_FTIGER_REFRESH] = "sc_ftiger_refresh"

CS_FTIGER_DRAW = 13211
PROTO_MAP[CS_FTIGER_DRAW] = "cs_ftiger_draw"

SC_FTIGER_DRAW = 13212
PROTO_MAP[SC_FTIGER_DRAW] = "sc_ftiger_draw"

CS_POWERRANK_OPEN = 13301
PROTO_MAP[CS_POWERRANK_OPEN] = "cs_powerrank_open"

SC_POWERRANK_OPEN = 13302
PROTO_MAP[SC_POWERRANK_OPEN] = "sc_powerrank_open"

CS_POWERRANK_LIST = 13303
PROTO_MAP[CS_POWERRANK_LIST] = "cs_powerrank_list"

SC_POWERRANK_LIST = 13304
PROTO_MAP[SC_POWERRANK_LIST] = "sc_powerrank_list"

CS_SYSRANK_FIGHTPOWER = 13402
PROTO_MAP[CS_SYSRANK_FIGHTPOWER] = "cs_sysrank_fightpower"

SC_SYSRANK_FIGHTPOWER = 13403
PROTO_MAP[SC_SYSRANK_FIGHTPOWER] = "sc_sysrank_fightpower"

CS_SYSRANK_ADVSTAR = 13405
PROTO_MAP[CS_SYSRANK_ADVSTAR] = "cs_sysrank_advstar"

SC_SYSRANK_ADVSTAR = 13406
PROTO_MAP[SC_SYSRANK_ADVSTAR] = "sc_sysrank_advstar"

CS_SYSRANK_GERPOKDEX = 13408
PROTO_MAP[CS_SYSRANK_GERPOKDEX] = "cs_sysrank_gerpokdex"

SC_SYSRANK_GERPOKDEX = 13409
PROTO_MAP[SC_SYSRANK_GERPOKDEX] = "sc_sysrank_gerpokdex"

CS_SYSRANK_TOPGER = 13411
PROTO_MAP[CS_SYSRANK_TOPGER] = "cs_sysrank_topger"

SC_SYSRANK_TOPGER = 13412
PROTO_MAP[SC_SYSRANK_TOPGER] = "sc_sysrank_topger"

CS_SYSRANK_TOPFAMILY = 13414
PROTO_MAP[CS_SYSRANK_TOPFAMILY] = "cs_sysrank_topfamily"

SC_SYSRANK_TOPFAMILY = 13415
PROTO_MAP[SC_SYSRANK_TOPFAMILY] = "sc_sysrank_topfamily"

CS_SYSRANK_FAMILY_SUMMARY = 13417
PROTO_MAP[CS_SYSRANK_FAMILY_SUMMARY] = "cs_sysrank_family_summary"

SC_SYSRANK_FAMILY_SUMMARY = 13418
PROTO_MAP[SC_SYSRANK_FAMILY_SUMMARY] = "sc_sysrank_family_summary"

CS_SIGN_INFO = 13501
PROTO_MAP[CS_SIGN_INFO] = "cs_sign_info"

SC_SIGN_INFO = 13502
PROTO_MAP[SC_SIGN_INFO] = "sc_sign_info"

CS_SIGN_DRAW = 13506
PROTO_MAP[CS_SIGN_DRAW] = "cs_sign_draw"

SC_SIGN_DRAW = 13507
PROTO_MAP[SC_SIGN_DRAW] = "sc_sign_draw"

CS_SIGN_DRAW_ADD = 13508
PROTO_MAP[CS_SIGN_DRAW_ADD] = "cs_sign_draw_add"

SC_SIGN_DRAW_ADD = 13509
PROTO_MAP[SC_SIGN_DRAW_ADD] = "sc_sign_draw_add"

CS_HOTMSG_LIST = 13601
PROTO_MAP[CS_HOTMSG_LIST] = "cs_hotmsg_list"

SC_HOTMSG_LIST = 13602
PROTO_MAP[SC_HOTMSG_LIST] = "sc_hotmsg_list"

CS_RENVELOPE_INFO = 13701
PROTO_MAP[CS_RENVELOPE_INFO] = "cs_renvelope_info"

SC_RENVELOPE_INFO = 13702
PROTO_MAP[SC_RENVELOPE_INFO] = "sc_renvelope_info"

CS_RENVELOPE_ROB = 13704
PROTO_MAP[CS_RENVELOPE_ROB] = "cs_renvelope_rob"

SC_RENVELOPE_ROB = 13705
PROTO_MAP[SC_RENVELOPE_ROB] = "sc_renvelope_rob"

SC_RENVELOPE_XHD = 13706
PROTO_MAP[SC_RENVELOPE_XHD] = "sc_renvelope_xhd"

CS_RENVELOPE_XHD = 13707
PROTO_MAP[CS_RENVELOPE_XHD] = "cs_renvelope_xhd"

CS_FRIEND_INFO = 13801
PROTO_MAP[CS_FRIEND_INFO] = "cs_friend_info"

SC_FRIEND_INFO = 13802
PROTO_MAP[SC_FRIEND_INFO] = "sc_friend_info"

CS_FRIEND_SEARCH = 13803
PROTO_MAP[CS_FRIEND_SEARCH] = "cs_friend_search"

SC_FRIEND_SEARCH = 13804
PROTO_MAP[SC_FRIEND_SEARCH] = "sc_friend_search"

CS_FRIEND_SEND_APPLY = 13805
PROTO_MAP[CS_FRIEND_SEND_APPLY] = "cs_friend_send_apply"

SC_FRIEND_SEND_APPLY = 13806
PROTO_MAP[SC_FRIEND_SEND_APPLY] = "sc_friend_send_apply"

CS_FRIEND_HANDLE_APPLY = 13807
PROTO_MAP[CS_FRIEND_HANDLE_APPLY] = "cs_friend_handle_apply"

SC_FRIEND_HANDLE_APPLY = 13808
PROTO_MAP[SC_FRIEND_HANDLE_APPLY] = "sc_friend_handle_apply"

CS_FRIEND_DELETE = 13809
PROTO_MAP[CS_FRIEND_DELETE] = "cs_friend_delete"

SC_FRIEND_DELETE = 13810
PROTO_MAP[SC_FRIEND_DELETE] = "sc_friend_delete"

SC_FRIEND_MSG = 13811
PROTO_MAP[SC_FRIEND_MSG] = "sc_friend_msg"

CS_FRIEND_MSG = 13812
PROTO_MAP[CS_FRIEND_MSG] = "cs_friend_msg"

CS_FRIEND_SEND_MSG = 13813
PROTO_MAP[CS_FRIEND_SEND_MSG] = "cs_friend_send_msg"

SC_FRIEND_SEND_MSG = 13814
PROTO_MAP[SC_FRIEND_SEND_MSG] = "sc_friend_send_msg"

CS_FRIEND_SEND_ENERGY = 13815
PROTO_MAP[CS_FRIEND_SEND_ENERGY] = "cs_friend_send_energy"

SC_FRIEND_SEND_ENERGY = 13816
PROTO_MAP[SC_FRIEND_SEND_ENERGY] = "sc_friend_send_energy"

CS_FRIEND_DRAW_ENERGY = 13817
PROTO_MAP[CS_FRIEND_DRAW_ENERGY] = "cs_friend_draw_energy"

SC_FRIEND_DRAW_ENERGY = 13818
PROTO_MAP[SC_FRIEND_DRAW_ENERGY] = "sc_friend_draw_energy"

CS_FRIEND_DRAW_ENERGY_AND_RETURN_ONEKEY = 13819
PROTO_MAP[CS_FRIEND_DRAW_ENERGY_AND_RETURN_ONEKEY] = "cs_friend_draw_energy_and_return_onekey"

SC_FRIEND_DRAW_ENERGY_AND_RETURN_ONEKEY = 13820
PROTO_MAP[SC_FRIEND_DRAW_ENERGY_AND_RETURN_ONEKEY] = "sc_friend_draw_energy_and_return_onekey"

CS_FRIEND_CHALLENGE = 13821
PROTO_MAP[CS_FRIEND_CHALLENGE] = "cs_friend_challenge"

SC_FRIEND_CHALLENGE = 13822
PROTO_MAP[SC_FRIEND_CHALLENGE] = "sc_friend_challenge"

CS_FRIEND_SEND_ENERGY_ONEKEY = 13823
PROTO_MAP[CS_FRIEND_SEND_ENERGY_ONEKEY] = "cs_friend_send_energy_onekey"

SC_FRIEND_SEND_ENERGY_ONEKEY = 13824
PROTO_MAP[SC_FRIEND_SEND_ENERGY_ONEKEY] = "sc_friend_send_energy_onekey"

SC_FRIEND_ADD_NOTIFY = 13857
PROTO_MAP[SC_FRIEND_ADD_NOTIFY] = "sc_friend_add_notify"

SC_FRIEND_DEL_NOTIFY = 13858
PROTO_MAP[SC_FRIEND_DEL_NOTIFY] = "sc_friend_del_notify"

SC_FRIEND_STATE_TRANS_NOTIFY = 13859
PROTO_MAP[SC_FRIEND_STATE_TRANS_NOTIFY] = "sc_friend_state_trans_notify"

CS_BOSS_INFO = 13901
PROTO_MAP[CS_BOSS_INFO] = "cs_boss_info"

SC_BOSS_INFO = 13902
PROTO_MAP[SC_BOSS_INFO] = "sc_boss_info"

CS_BOSS_QUIT = 13904
PROTO_MAP[CS_BOSS_QUIT] = "cs_boss_quit"

SC_BOSS_QUIT = 13905
PROTO_MAP[SC_BOSS_QUIT] = "sc_boss_quit"

CS_BOSS_DRAW = 13906
PROTO_MAP[CS_BOSS_DRAW] = "cs_boss_draw"

SC_BOSS_DRAW = 13907
PROTO_MAP[SC_BOSS_DRAW] = "sc_boss_draw"

CS_BOSS_FIGHT = 13908
PROTO_MAP[CS_BOSS_FIGHT] = "cs_boss_fight"

SC_BOSS_FIGHT = 13909
PROTO_MAP[SC_BOSS_FIGHT] = "sc_boss_fight"

CS_BOSS_TOPS = 13910
PROTO_MAP[CS_BOSS_TOPS] = "cs_boss_tops"

SC_BOSS_TOPS = 13911
PROTO_MAP[SC_BOSS_TOPS] = "sc_boss_tops"

SC_PLAYER_HARM = 13913
PROTO_MAP[SC_PLAYER_HARM] = "sc_player_harm"

CS_BOSS_SELVIP = 13914
PROTO_MAP[CS_BOSS_SELVIP] = "cs_boss_selvip"

SC_BOSS_SELVIP = 13915
PROTO_MAP[SC_BOSS_SELVIP] = "sc_boss_selvip"

CS_BOSS_HARM = 13916
PROTO_MAP[CS_BOSS_HARM] = "cs_boss_harm"

SC_BOSS_HARM = 13917
PROTO_MAP[SC_BOSS_HARM] = "sc_boss_harm"

SC_BOSS_STATE_UPDATE = 13918
PROTO_MAP[SC_BOSS_STATE_UPDATE] = "sc_boss_state_update"

CS_DIGIVICE_INFO = 14001
PROTO_MAP[CS_DIGIVICE_INFO] = "cs_digivice_info"

SC_DIGIVICE_INFO = 14002
PROTO_MAP[SC_DIGIVICE_INFO] = "sc_digivice_info"

CS_DIGIVICE_REINFORCE = 14006
PROTO_MAP[CS_DIGIVICE_REINFORCE] = "cs_digivice_reinforce"

SC_DIGIVICE_REINFORCE = 14007
PROTO_MAP[SC_DIGIVICE_REINFORCE] = "sc_digivice_reinforce"

SC_DIGIVICE_NOTIFY = 14008
PROTO_MAP[SC_DIGIVICE_NOTIFY] = "sc_digivice_notify"

CS_DIGIVICE_REFINE = 14009
PROTO_MAP[CS_DIGIVICE_REFINE] = "cs_digivice_refine"

SC_DIGIVICE_REFINE = 14010
PROTO_MAP[SC_DIGIVICE_REFINE] = "sc_digivice_refine"

CS_DIGIVICE_REPLACE = 14011
PROTO_MAP[CS_DIGIVICE_REPLACE] = "cs_digivice_replace"

SC_DIGIVICE_REPLACE = 14012
PROTO_MAP[SC_DIGIVICE_REPLACE] = "sc_digivice_replace"

CS_DIGIVICE_REPLACE_GIVEUP = 14014
PROTO_MAP[CS_DIGIVICE_REPLACE_GIVEUP] = "cs_digivice_replace_giveup"

SC_DIGIVICE_REPLACE_GIVEUP = 14015
PROTO_MAP[SC_DIGIVICE_REPLACE_GIVEUP] = "sc_digivice_replace_giveup"

CS_RMBGIFT_INFO = 14101
PROTO_MAP[CS_RMBGIFT_INFO] = "cs_rmbgift_info"

SC_RMBGIFT_INFO = 14102
PROTO_MAP[SC_RMBGIFT_INFO] = "sc_rmbgift_info"

CS_MINE_INFO = 14201
PROTO_MAP[CS_MINE_INFO] = "cs_mine_info"

SC_MINE_INFO = 14202
PROTO_MAP[SC_MINE_INFO] = "sc_mine_info"

CS_MINE_REFRESH = 14204
PROTO_MAP[CS_MINE_REFRESH] = "cs_mine_refresh"

SC_MINE_REFRESH = 14205
PROTO_MAP[SC_MINE_REFRESH] = "sc_mine_refresh"

CS_MINE_BUY = 14206
PROTO_MAP[CS_MINE_BUY] = "cs_mine_buy"

SC_MINE_BUY = 14207
PROTO_MAP[SC_MINE_BUY] = "sc_mine_buy"

CS_MINE_DIG = 14208
PROTO_MAP[CS_MINE_DIG] = "cs_mine_dig"

SC_MINE_DIG = 14209
PROTO_MAP[SC_MINE_DIG] = "sc_mine_dig"

CS_MINE_VIEW = 14210
PROTO_MAP[CS_MINE_VIEW] = "cs_mine_view"

SC_MINE_VIEW = 14211
PROTO_MAP[SC_MINE_VIEW] = "sc_mine_view"

CS_MINE_EXPLORE = 14212
PROTO_MAP[CS_MINE_EXPLORE] = "cs_mine_explore"

SC_MINE_EXPLORE = 14213
PROTO_MAP[SC_MINE_EXPLORE] = "sc_mine_explore"

CS_MINE_ATTACK_REQUEST = 14216
PROTO_MAP[CS_MINE_ATTACK_REQUEST] = "cs_mine_attack_request"

SC_MINE_ATTACK_REQUEST = 14217
PROTO_MAP[SC_MINE_ATTACK_REQUEST] = "sc_mine_attack_request"

CS_MINE_ATTACK_REPORT = 14218
PROTO_MAP[CS_MINE_ATTACK_REPORT] = "cs_mine_attack_report"

SC_MINE_ATTACK_REPORT = 14219
PROTO_MAP[SC_MINE_ATTACK_REPORT] = "sc_mine_attack_report"

CS_MINE_HIST = 14220
PROTO_MAP[CS_MINE_HIST] = "cs_mine_hist"

SC_MINE_HIST = 14221
PROTO_MAP[SC_MINE_HIST] = "sc_mine_hist"

CS_MINE_INVITE = 14223
PROTO_MAP[CS_MINE_INVITE] = "cs_mine_invite"

SC_MINE_INVITE = 14224
PROTO_MAP[SC_MINE_INVITE] = "sc_mine_invite"

CS_MINE_JOIN_VIEW = 14225
PROTO_MAP[CS_MINE_JOIN_VIEW] = "cs_mine_join_view"

SC_MINE_JOIN_VIEW = 14226
PROTO_MAP[SC_MINE_JOIN_VIEW] = "sc_mine_join_view"

CS_MINE_OPEN = 14227
PROTO_MAP[CS_MINE_OPEN] = "cs_mine_open"

SC_MINE_OPEN = 14228
PROTO_MAP[SC_MINE_OPEN] = "sc_mine_open"

CS_MINE_GUARD = 14230
PROTO_MAP[CS_MINE_GUARD] = "cs_mine_guard"

SC_MINE_GUARD = 14231
PROTO_MAP[SC_MINE_GUARD] = "sc_mine_guard"

CS_MINE_DRAW = 14232
PROTO_MAP[CS_MINE_DRAW] = "cs_mine_draw"

SC_MINE_DRAW = 14233
PROTO_MAP[SC_MINE_DRAW] = "sc_mine_draw"

SC_MINE_NOTIFY = 14234
PROTO_MAP[SC_MINE_NOTIFY] = "sc_mine_notify"

CS_MINE_VIEW_REWARD = 14235
PROTO_MAP[CS_MINE_VIEW_REWARD] = "cs_mine_view_reward"

SC_MINE_VIEW_REWARD = 14236
PROTO_MAP[SC_MINE_VIEW_REWARD] = "sc_mine_view_reward"

CS_HEGEMONY_ACTIVITY_INFO = 14243
PROTO_MAP[CS_HEGEMONY_ACTIVITY_INFO] = "cs_hegemony_activity_info"

SC_HEGEMONY_ACTIVITY_INFO = 14244
PROTO_MAP[SC_HEGEMONY_ACTIVITY_INFO] = "sc_hegemony_activity_info"

CS_HEGEMONY_ACTIVITY_DRAW = 14245
PROTO_MAP[CS_HEGEMONY_ACTIVITY_DRAW] = "cs_hegemony_activity_draw"

SC_HEGEMONY_ACTIVITY_DRAW = 14246
PROTO_MAP[SC_HEGEMONY_ACTIVITY_DRAW] = "sc_hegemony_activity_draw"

CS_HEGEMONY_ACTIVITY_DRAWEND = 14247
PROTO_MAP[CS_HEGEMONY_ACTIVITY_DRAWEND] = "cs_hegemony_activity_drawend"

SC_HEGEMONY_ACTIVITY_DRAWEND = 14248
PROTO_MAP[SC_HEGEMONY_ACTIVITY_DRAWEND] = "sc_hegemony_activity_drawend"

SC_HEGEMONY_ACTIVITY_NOTIFY = 14249
PROTO_MAP[SC_HEGEMONY_ACTIVITY_NOTIFY] = "sc_hegemony_activity_notify"

CS_HEGEMONY_JOIN_VIEW = 14250
PROTO_MAP[CS_HEGEMONY_JOIN_VIEW] = "cs_hegemony_join_view"

CS_HEGEMONY_LEAVE_VIEW = 14251
PROTO_MAP[CS_HEGEMONY_LEAVE_VIEW] = "cs_hegemony_leave_view"

CS_HIST_SHARE = 14301
PROTO_MAP[CS_HIST_SHARE] = "cs_hist_share"

SC_HIST_SHARE = 14302
PROTO_MAP[SC_HIST_SHARE] = "sc_hist_share"

CS_HIST_WATCH = 14303
PROTO_MAP[CS_HIST_WATCH] = "cs_hist_watch"

SC_HIST_WATCH = 14304
PROTO_MAP[SC_HIST_WATCH] = "sc_hist_watch"

CS_PRAY_INFO = 14401
PROTO_MAP[CS_PRAY_INFO] = "cs_pray_info"

SC_PRAY_INFO = 14402
PROTO_MAP[SC_PRAY_INFO] = "sc_pray_info"

CS_PRAY_RANK = 14403
PROTO_MAP[CS_PRAY_RANK] = "cs_pray_rank"

SC_PRAY_RANK = 14404
PROTO_MAP[SC_PRAY_RANK] = "sc_pray_rank"

CS_PRAY_DO = 14405
PROTO_MAP[CS_PRAY_DO] = "cs_pray_do"

SC_PRAY_DO = 14406
PROTO_MAP[SC_PRAY_DO] = "sc_pray_do"

CS_PRAY_DRAW = 14407
PROTO_MAP[CS_PRAY_DRAW] = "cs_pray_draw"

SC_PRAY_DRAW = 14408
PROTO_MAP[SC_PRAY_DRAW] = "sc_pray_draw"

SC_PRAY_STATE = 14409
PROTO_MAP[SC_PRAY_STATE] = "sc_pray_state"

CS_FIELD_INFO = 14501
PROTO_MAP[CS_FIELD_INFO] = "cs_field_info"

SC_FIELD_INFO = 14502
PROTO_MAP[SC_FIELD_INFO] = "sc_field_info"

CS_FIELD_UPLV = 14504
PROTO_MAP[CS_FIELD_UPLV] = "cs_field_uplv"

SC_FIELD_UPLV = 14505
PROTO_MAP[SC_FIELD_UPLV] = "sc_field_uplv"

CS_FIELD_DECOMPOSE = 14506
PROTO_MAP[CS_FIELD_DECOMPOSE] = "cs_field_decompose"

SC_FIELD_DECOMPOSE = 14507
PROTO_MAP[SC_FIELD_DECOMPOSE] = "sc_field_decompose"

CS_FIELD_CHANGE = 14508
PROTO_MAP[CS_FIELD_CHANGE] = "cs_field_change"

SC_FIELD_CHANGE = 14509
PROTO_MAP[SC_FIELD_CHANGE] = "sc_field_change"

CS_FIELD_SET = 14510
PROTO_MAP[CS_FIELD_SET] = "cs_field_set"

SC_FIELD_SET = 14511
PROTO_MAP[SC_FIELD_SET] = "sc_field_set"

CS_FIELD_ALLUN = 14512
PROTO_MAP[CS_FIELD_ALLUN] = "cs_field_allun"

SC_FIELD_ALLUN = 14513
PROTO_MAP[SC_FIELD_ALLUN] = "sc_field_allun"

CS_FIELD_EQUIP_CHANGE = 14514
PROTO_MAP[CS_FIELD_EQUIP_CHANGE] = "cs_field_equip_change"

SC_FIELD_EQUIP_CHANGE = 14515
PROTO_MAP[SC_FIELD_EQUIP_CHANGE] = "sc_field_equip_change"

CS_CHASER_ENTER = 14601
PROTO_MAP[CS_CHASER_ENTER] = "cs_chaser_enter"

SC_CHASER_ENTER = 14602
PROTO_MAP[SC_CHASER_ENTER] = "sc_chaser_enter"

CS_CHASER_NEW_TEAMUP = 14604
PROTO_MAP[CS_CHASER_NEW_TEAMUP] = "cs_chaser_new_teamup"

SC_CHASER_NEW_TEAMUP = 14605
PROTO_MAP[SC_CHASER_NEW_TEAMUP] = "sc_chaser_new_teamup"

CS_CHASER_QUICK_JOIN = 14606
PROTO_MAP[CS_CHASER_QUICK_JOIN] = "cs_chaser_quick_join"

SC_CHASER_QUICK_JOIN = 14607
PROTO_MAP[SC_CHASER_QUICK_JOIN] = "sc_chaser_quick_join"

CS_CHASER_LEAVE = 14608
PROTO_MAP[CS_CHASER_LEAVE] = "cs_chaser_leave"

SC_CHASER_LEAVE = 14609
PROTO_MAP[SC_CHASER_LEAVE] = "sc_chaser_leave"

CS_CHASER_INVITE = 14610
PROTO_MAP[CS_CHASER_INVITE] = "cs_chaser_invite"

SC_CHASER_INVITE = 14611
PROTO_MAP[SC_CHASER_INVITE] = "sc_chaser_invite"

CS_CHASER_JOIN = 14612
PROTO_MAP[CS_CHASER_JOIN] = "cs_chaser_join"

SC_CHASER_JOIN = 14613
PROTO_MAP[SC_CHASER_JOIN] = "sc_chaser_join"

CS_CHASER_GER_EXCHANGE = 14614
PROTO_MAP[CS_CHASER_GER_EXCHANGE] = "cs_chaser_ger_exchange"

SC_CHASER_GER_EXCHANGE = 14615
PROTO_MAP[SC_CHASER_GER_EXCHANGE] = "sc_chaser_ger_exchange"

CS_CHASER_EMBATTLE = 14616
PROTO_MAP[CS_CHASER_EMBATTLE] = "cs_chaser_embattle"

SC_CHASER_EMBATTLE = 14617
PROTO_MAP[SC_CHASER_EMBATTLE] = "sc_chaser_embattle"

CS_CHASER_GER_MOVPOS = 14618
PROTO_MAP[CS_CHASER_GER_MOVPOS] = "cs_chaser_ger_movpos"

SC_CHASER_GER_MOVPOS = 14619
PROTO_MAP[SC_CHASER_GER_MOVPOS] = "sc_chaser_ger_movpos"

CS_CHASER_FIGHT = 14620
PROTO_MAP[CS_CHASER_FIGHT] = "cs_chaser_fight"

SC_CHASER_FIGHT = 14621
PROTO_MAP[SC_CHASER_FIGHT] = "sc_chaser_fight"

CS_CHASER_FIGHT_BACK = 14622
PROTO_MAP[CS_CHASER_FIGHT_BACK] = "cs_chaser_fight_back"

SC_CHASER_FIGHT_BACK = 14623
PROTO_MAP[SC_CHASER_FIGHT_BACK] = "sc_chaser_fight_back"

SC_CHASER_NOTIFY = 14624
PROTO_MAP[SC_CHASER_NOTIFY] = "sc_chaser_notify"

CS_SGAME_INFO = 14701
PROTO_MAP[CS_SGAME_INFO] = "cs_sgame_info"

SC_SGAME_INFO = 14702
PROTO_MAP[SC_SGAME_INFO] = "sc_sgame_info"

CS_SGAME_REWARD = 14703
PROTO_MAP[CS_SGAME_REWARD] = "cs_sgame_reward"

SC_SGAME_REWARD = 14704
PROTO_MAP[SC_SGAME_REWARD] = "sc_sgame_reward"

CS_SGAME_BUYTIMES = 14706
PROTO_MAP[CS_SGAME_BUYTIMES] = "cs_sgame_buytimes"

SC_SGAME_BUYTIMES = 14707
PROTO_MAP[SC_SGAME_BUYTIMES] = "sc_sgame_buytimes"

CS_SGAME_ENTER = 14708
PROTO_MAP[CS_SGAME_ENTER] = "cs_sgame_enter"

SC_SGAME_ENTER = 14709
PROTO_MAP[SC_SGAME_ENTER] = "sc_sgame_enter"

CS_SGAME_DRAW = 14710
PROTO_MAP[CS_SGAME_DRAW] = "cs_sgame_draw"

SC_SGAME_DRAW = 14711
PROTO_MAP[SC_SGAME_DRAW] = "sc_sgame_draw"

CS_SGAME_ONEKEY = 14712
PROTO_MAP[CS_SGAME_ONEKEY] = "cs_sgame_onekey"

SC_SGAME_ONEKEY = 14713
PROTO_MAP[SC_SGAME_ONEKEY] = "sc_sgame_onekey"

SC_SGAME_NOTIFY = 14714
PROTO_MAP[SC_SGAME_NOTIFY] = "sc_sgame_notify"

CS_SGAME_OVER = 14715
PROTO_MAP[CS_SGAME_OVER] = "cs_sgame_over"

SC_SGAME_OVER = 14716
PROTO_MAP[SC_SGAME_OVER] = "sc_sgame_over"

SC_SGAME_NUM_NOTIFY = 14719
PROTO_MAP[SC_SGAME_NUM_NOTIFY] = "sc_sgame_num_notify"

CS_PERTERR_TUPO = 14804
PROTO_MAP[CS_PERTERR_TUPO] = "cs_perterr_tupo"

SC_PERTERR_TUPO = 14805
PROTO_MAP[SC_PERTERR_TUPO] = "sc_perterr_tupo"

CS_PERTERR_SWITCH_TITLE = 14806
PROTO_MAP[CS_PERTERR_SWITCH_TITLE] = "cs_perterr_switch_title"

SC_PERTERR_SWITCH_TITLE = 14807
PROTO_MAP[SC_PERTERR_SWITCH_TITLE] = "sc_perterr_switch_title"

CS_PERTERR_RECYCLE = 14808
PROTO_MAP[CS_PERTERR_RECYCLE] = "cs_perterr_recycle"

SC_PERTERR_RECYCLE = 14809
PROTO_MAP[SC_PERTERR_RECYCLE] = "sc_perterr_recycle"

CS_PERTERR_ANNOUNCE = 14810
PROTO_MAP[CS_PERTERR_ANNOUNCE] = "cs_perterr_announce"

SC_PERTERR_ANNOUNCE = 14811
PROTO_MAP[SC_PERTERR_ANNOUNCE] = "sc_perterr_announce"

CS_PERTERR_INFO = 14812
PROTO_MAP[CS_PERTERR_INFO] = "cs_perterr_info"

SC_PERTERR_INFO = 14813
PROTO_MAP[SC_PERTERR_INFO] = "sc_perterr_info"

CS_PERTERR_OPENSHOP = 14819
PROTO_MAP[CS_PERTERR_OPENSHOP] = "cs_perterr_openshop"

SC_PERTERR_OPENSHOP = 14820
PROTO_MAP[SC_PERTERR_OPENSHOP] = "sc_perterr_openshop"

CS_PERTERR_COLLECT = 14822
PROTO_MAP[CS_PERTERR_COLLECT] = "cs_perterr_collect"

SC_PERTERR_COLLECT = 14823
PROTO_MAP[SC_PERTERR_COLLECT] = "sc_perterr_collect"

CS_PERTERR_FOSTER = 14824
PROTO_MAP[CS_PERTERR_FOSTER] = "cs_perterr_foster"

SC_PERTERR_FOSTER = 14825
PROTO_MAP[SC_PERTERR_FOSTER] = "sc_perterr_foster"

CS_PERTERR_PROD_UPLV = 14826
PROTO_MAP[CS_PERTERR_PROD_UPLV] = "cs_perterr_prod_uplv"

SC_PERTERR_PROD_UPLV = 14827
PROTO_MAP[SC_PERTERR_PROD_UPLV] = "sc_perterr_prod_uplv"

CS_PERTERR_FRIEND = 14828
PROTO_MAP[CS_PERTERR_FRIEND] = "cs_perterr_friend"

SC_PERTERR_FRIEND = 14829
PROTO_MAP[SC_PERTERR_FRIEND] = "sc_perterr_friend"

CS_PERTERR_FOSTERDRAW = 14831
PROTO_MAP[CS_PERTERR_FOSTERDRAW] = "cs_perterr_fosterdraw"

SC_PERTERR_FOSTERDRAW = 14832
PROTO_MAP[SC_PERTERR_FOSTERDRAW] = "sc_perterr_fosterdraw"

CS_PERTERR_RCLE_UPLV = 14833
PROTO_MAP[CS_PERTERR_RCLE_UPLV] = "cs_perterr_rcle_uplv"

SC_PERTERR_RCLE_UPLV = 14834
PROTO_MAP[SC_PERTERR_RCLE_UPLV] = "sc_perterr_rcle_uplv"

CS_PERTERR_GETPROD = 14835
PROTO_MAP[CS_PERTERR_GETPROD] = "cs_perterr_getprod"

SC_PERTERR_GETPROD = 14836
PROTO_MAP[SC_PERTERR_GETPROD] = "sc_perterr_getprod"

CS_PERTERR_SKILLUPLV = 14837
PROTO_MAP[CS_PERTERR_SKILLUPLV] = "cs_perterr_skilluplv"

SC_PERTERR_SKILLUPLV = 14838
PROTO_MAP[SC_PERTERR_SKILLUPLV] = "sc_perterr_skilluplv"

CS_PERTERR_GETSKILL = 14839
PROTO_MAP[CS_PERTERR_GETSKILL] = "cs_perterr_getskill"

SC_PERTERR_GETSKILL = 14840
PROTO_MAP[SC_PERTERR_GETSKILL] = "sc_perterr_getskill"

CS_PERTERR_INVITE_FOSTER = 14841
PROTO_MAP[CS_PERTERR_INVITE_FOSTER] = "cs_perterr_invite_foster"

SC_PERTERR_INVITE_FOSTER = 14842
PROTO_MAP[SC_PERTERR_INVITE_FOSTER] = "sc_perterr_invite_foster"

CS_FTERRITORY_INFO = 14901
PROTO_MAP[CS_FTERRITORY_INFO] = "cs_fterritory_info"

SC_FTERRITORY_INFO = 14902
PROTO_MAP[SC_FTERRITORY_INFO] = "sc_fterritory_info"

CS_FTERRITORY_TASKDRAW = 14904
PROTO_MAP[CS_FTERRITORY_TASKDRAW] = "cs_fterritory_taskdraw"

SC_FTERRITORY_TASKDRAW = 14905
PROTO_MAP[SC_FTERRITORY_TASKDRAW] = "sc_fterritory_taskdraw"

CS_FTERRITORY_SHOPBUY = 14906
PROTO_MAP[CS_FTERRITORY_SHOPBUY] = "cs_fterritory_shopbuy"

SC_FTERRITORY_SHOPBUY = 14907
PROTO_MAP[SC_FTERRITORY_SHOPBUY] = "sc_fterritory_shopbuy"

CS_FTERRITORY_UPLEVEL = 14908
PROTO_MAP[CS_FTERRITORY_UPLEVEL] = "cs_fterritory_uplevel"

SC_FTERRITORY_UPLEVEL = 14909
PROTO_MAP[SC_FTERRITORY_UPLEVEL] = "sc_fterritory_uplevel"

CS_FTERRITORY_SWITCH = 14910
PROTO_MAP[CS_FTERRITORY_SWITCH] = "cs_fterritory_switch"

SC_FTERRITORY_SWITCH = 14911
PROTO_MAP[SC_FTERRITORY_SWITCH] = "sc_fterritory_switch"

SC_FTER_PMANSION_NOTIFY = 14912
PROTO_MAP[SC_FTER_PMANSION_NOTIFY] = "sc_fter_pmansion_notify"

SC_FTER_TASK_NOTIFY = 14913
PROTO_MAP[SC_FTER_TASK_NOTIFY] = "sc_fter_task_notify"

SC_FTSHOP_NOTIFY = 14914
PROTO_MAP[SC_FTSHOP_NOTIFY] = "sc_ftshop_notify"

CS_FTERRITORY_SWITCHBACK = 14915
PROTO_MAP[CS_FTERRITORY_SWITCHBACK] = "cs_fterritory_switchback"

SC_FTERRITORY_SWITCHBACK = 14916
PROTO_MAP[SC_FTERRITORY_SWITCHBACK] = "sc_fterritory_switchback"

SC_FTER_SWITCH_NOTIFY = 14918
PROTO_MAP[SC_FTER_SWITCH_NOTIFY] = "sc_fter_switch_notify"

SC_FTER_BUFF_NOTIFY = 14919
PROTO_MAP[SC_FTER_BUFF_NOTIFY] = "sc_fter_buff_notify"

CS_FTERRITORY_HTASK = 14921
PROTO_MAP[CS_FTERRITORY_HTASK] = "cs_fterritory_htask"

SC_FTERRITORY_HTASK = 14922
PROTO_MAP[SC_FTERRITORY_HTASK] = "sc_fterritory_htask"

SC_FTERRITORY_FHANGUP_TASK_NOTIFY = 14924
PROTO_MAP[SC_FTERRITORY_FHANGUP_TASK_NOTIFY] = "sc_fterritory_fhangup_task_notify"

CS_FTERRITORY_FHANGUP_ACTIVE = 14925
PROTO_MAP[CS_FTERRITORY_FHANGUP_ACTIVE] = "cs_fterritory_fhangup_active"

SC_FTERRITORY_FHANGUP_ACTIVE = 14926
PROTO_MAP[SC_FTERRITORY_FHANGUP_ACTIVE] = "sc_fterritory_fhangup_active"

CS_FTERRITORY_FHANGUP_TASKDRAW = 14927
PROTO_MAP[CS_FTERRITORY_FHANGUP_TASKDRAW] = "cs_fterritory_fhangup_taskdraw"

SC_FTERRITORY_FHANGUP_TASKDRAW = 14928
PROTO_MAP[SC_FTERRITORY_FHANGUP_TASKDRAW] = "sc_fterritory_fhangup_taskdraw"

CS_FCROSS_ENROL = 15001
PROTO_MAP[CS_FCROSS_ENROL] = "cs_fcross_enrol"

SC_FCROSS_ENROL = 15002
PROTO_MAP[SC_FCROSS_ENROL] = "sc_fcross_enrol"

CS_FCROSS_INSPIRE = 15003
PROTO_MAP[CS_FCROSS_INSPIRE] = "cs_fcross_inspire"

SC_FCROSS_INSPIRE = 15004
PROTO_MAP[SC_FCROSS_INSPIRE] = "sc_fcross_inspire"

CS_FCROSS_DISPOSAL = 15005
PROTO_MAP[CS_FCROSS_DISPOSAL] = "cs_fcross_disposal"

SC_FCROSS_DISPOSAL = 15006
PROTO_MAP[SC_FCROSS_DISPOSAL] = "sc_fcross_disposal"

CS_FCROSS_BATTLEFIELD = 15007
PROTO_MAP[CS_FCROSS_BATTLEFIELD] = "cs_fcross_battlefield"

SC_FCROSS_BATTLEFIELD = 15008
PROTO_MAP[SC_FCROSS_BATTLEFIELD] = "sc_fcross_battlefield"

CS_FCROSS_TEAM = 15010
PROTO_MAP[CS_FCROSS_TEAM] = "cs_fcross_team"

SC_FCROSS_TEAM = 15011
PROTO_MAP[SC_FCROSS_TEAM] = "sc_fcross_team"

CS_FCROSS_INSPIREINFO = 15012
PROTO_MAP[CS_FCROSS_INSPIREINFO] = "cs_fcross_inspireinfo"

SC_FCROSS_INSPIREINFO = 15013
PROTO_MAP[SC_FCROSS_INSPIREINFO] = "sc_fcross_inspireinfo"

CS_FCROSS_GETSTARS = 15015
PROTO_MAP[CS_FCROSS_GETSTARS] = "cs_fcross_getstars"

SC_FCROSS_GETSTARS = 15016
PROTO_MAP[SC_FCROSS_GETSTARS] = "sc_fcross_getstars"

CS_FCROSS_CHALLTIMES = 15018
PROTO_MAP[CS_FCROSS_CHALLTIMES] = "cs_fcross_challtimes"

SC_FCROSS_CHALLTIMES = 15019
PROTO_MAP[SC_FCROSS_CHALLTIMES] = "sc_fcross_challtimes"

CS_FCROSS_SCORERANK = 15021
PROTO_MAP[CS_FCROSS_SCORERANK] = "cs_fcross_scorerank"

SC_FCROSS_SCORERANK = 15022
PROTO_MAP[SC_FCROSS_SCORERANK] = "sc_fcross_scorerank"

CS_FCROSS_FAMILYREPLAY = 15024
PROTO_MAP[CS_FCROSS_FAMILYREPLAY] = "cs_fcross_familyreplay"

SC_FCROSS_FAMILYREPLAY = 15025
PROTO_MAP[SC_FCROSS_FAMILYREPLAY] = "sc_fcross_familyreplay"

CS_FCROSS_REPLAY = 15028
PROTO_MAP[CS_FCROSS_REPLAY] = "cs_fcross_replay"

SC_FCROSS_REPLAY = 15029
PROTO_MAP[SC_FCROSS_REPLAY] = "sc_fcross_replay"

CS_FCROSS_MARKENEMY = 15030
PROTO_MAP[CS_FCROSS_MARKENEMY] = "cs_fcross_markenemy"

SC_FCROSS_MARKENEMY = 15031
PROTO_MAP[SC_FCROSS_MARKENEMY] = "sc_fcross_markenemy"

CS_FCROSS_FIGHTREPLAY = 15033
PROTO_MAP[CS_FCROSS_FIGHTREPLAY] = "cs_fcross_fightreplay"

SC_FCROSS_FIGHTREPLAY = 15034
PROTO_MAP[SC_FCROSS_FIGHTREPLAY] = "sc_fcross_fightreplay"

CS_FCROSS_FIGHT = 15035
PROTO_MAP[CS_FCROSS_FIGHT] = "cs_fcross_fight"

SC_FCROSS_FIGHT = 15036
PROTO_MAP[SC_FCROSS_FIGHT] = "sc_fcross_fight"

CS_FCROSS_INFO = 15038
PROTO_MAP[CS_FCROSS_INFO] = "cs_fcross_info"

SC_FCROSS_INFO = 15039
PROTO_MAP[SC_FCROSS_INFO] = "sc_fcross_info"

CS_FCROSS_DEFINFO = 15044
PROTO_MAP[CS_FCROSS_DEFINFO] = "cs_fcross_definfo"

SC_FCROSS_DEFINFO = 15045
PROTO_MAP[SC_FCROSS_DEFINFO] = "sc_fcross_definfo"

SC_FCROSS_BCFIGHT = 15049
PROTO_MAP[SC_FCROSS_BCFIGHT] = "sc_fcross_bcfight"

CS_FCROSS_OPEN_BFIELD = 15050
PROTO_MAP[CS_FCROSS_OPEN_BFIELD] = "cs_fcross_open_bfield"

SC_FCROSS_OPEN_BFIELD = 15051
PROTO_MAP[SC_FCROSS_OPEN_BFIELD] = "sc_fcross_open_bfield"

SC_FCROSS_NOTIFY_ENROL = 15052
PROTO_MAP[SC_FCROSS_NOTIFY_ENROL] = "sc_fcross_notify_enrol"

SC_FCROSS_NOTIFY_STAGE = 15053
PROTO_MAP[SC_FCROSS_NOTIFY_STAGE] = "sc_fcross_notify_stage"

CS_EXTREME_INFO = 15101
PROTO_MAP[CS_EXTREME_INFO] = "cs_extreme_info"

SC_EXTREME_INFO = 15102
PROTO_MAP[SC_EXTREME_INFO] = "sc_extreme_info"

CS_EXTREME_MATCH = 15106
PROTO_MAP[CS_EXTREME_MATCH] = "cs_extreme_match"

SC_EXTREME_MATCH = 15107
PROTO_MAP[SC_EXTREME_MATCH] = "sc_extreme_match"

CS_EXTREME_MATCHCANCEL = 15111
PROTO_MAP[CS_EXTREME_MATCHCANCEL] = "cs_extreme_matchcancel"

SC_EXTREME_MATCHCANCEL = 15112
PROTO_MAP[SC_EXTREME_MATCHCANCEL] = "sc_extreme_matchcancel"

CS_EXTREME_RANK = 15113
PROTO_MAP[CS_EXTREME_RANK] = "cs_extreme_rank"

SC_EXTREME_RANK = 15114
PROTO_MAP[SC_EXTREME_RANK] = "sc_extreme_rank"

CS_EXTREME_TOTAL_RECORD = 15116
PROTO_MAP[CS_EXTREME_TOTAL_RECORD] = "cs_extreme_total_record"

SC_EXTREME_TOTAL_RECORD = 15117
PROTO_MAP[SC_EXTREME_TOTAL_RECORD] = "sc_extreme_total_record"

CS_EXTREME_MY_RECORD = 15118
PROTO_MAP[CS_EXTREME_MY_RECORD] = "cs_extreme_my_record"

SC_EXTREME_MY_RECORD = 15119
PROTO_MAP[SC_EXTREME_MY_RECORD] = "sc_extreme_my_record"

CS_EXTREME_REPLAYVIEW = 15120
PROTO_MAP[CS_EXTREME_REPLAYVIEW] = "cs_extreme_replayview"

SC_EXTREME_REPLAYVIEW = 15121
PROTO_MAP[SC_EXTREME_REPLAYVIEW] = "sc_extreme_replayview"

CS_EXTREME_STANDUP = 15123
PROTO_MAP[CS_EXTREME_STANDUP] = "cs_extreme_standup"

SC_EXTREME_STANDUP = 15124
PROTO_MAP[SC_EXTREME_STANDUP] = "sc_extreme_standup"

CS_EXTREME_BOXOPEN = 15126
PROTO_MAP[CS_EXTREME_BOXOPEN] = "cs_extreme_boxopen"

SC_EXTREME_BOXOPEN = 15127
PROTO_MAP[SC_EXTREME_BOXOPEN] = "sc_extreme_boxopen"

CS_EXTREME_QUICKOPEN = 15128
PROTO_MAP[CS_EXTREME_QUICKOPEN] = "cs_extreme_quickopen"

SC_EXTREME_QUICKOPEN = 15129
PROTO_MAP[SC_EXTREME_QUICKOPEN] = "sc_extreme_quickopen"

SC_EXTREME_NOTIFY_FREEBOX = 15130
PROTO_MAP[SC_EXTREME_NOTIFY_FREEBOX] = "sc_extreme_notify_freebox"

SC_EXTREME_NOTIFY_BOXWIN = 15131
PROTO_MAP[SC_EXTREME_NOTIFY_BOXWIN] = "sc_extreme_notify_boxwin"

SC_EXTREME_NOTIFY_BOXBATTLE = 15132
PROTO_MAP[SC_EXTREME_NOTIFY_BOXBATTLE] = "sc_extreme_notify_boxbattle"

SC_EXTREME_NOTIFY_INFO = 15134
PROTO_MAP[SC_EXTREME_NOTIFY_INFO] = "sc_extreme_notify_info"

CS_EXTREME_BATTLEBOX_UNLOCK = 15135
PROTO_MAP[CS_EXTREME_BATTLEBOX_UNLOCK] = "cs_extreme_battlebox_unlock"

SC_EXTREME_BATTLEBOX_UNLOCK = 15136
PROTO_MAP[SC_EXTREME_BATTLEBOX_UNLOCK] = "sc_extreme_battlebox_unlock"

SC_HIST_WATCH_EXTREME = 15137
PROTO_MAP[SC_HIST_WATCH_EXTREME] = "sc_hist_watch_extreme"

CS_STATUE_INFO = 15201
PROTO_MAP[CS_STATUE_INFO] = "cs_statue_info"

SC_STATUE_INFO = 15202
PROTO_MAP[SC_STATUE_INFO] = "sc_statue_info"

CS_STATUE_ACTIVE = 15203
PROTO_MAP[CS_STATUE_ACTIVE] = "cs_statue_active"

SC_STATUE_ACTIVE = 15204
PROTO_MAP[SC_STATUE_ACTIVE] = "sc_statue_active"

CS_STATUE_UNLOCK = 15207
PROTO_MAP[CS_STATUE_UNLOCK] = "cs_statue_unlock"

SC_STATUE_UNLOCK = 15208
PROTO_MAP[SC_STATUE_UNLOCK] = "sc_statue_unlock"

CS_STATUE_RATEINFO = 15209
PROTO_MAP[CS_STATUE_RATEINFO] = "cs_statue_rateinfo"

SC_STATUE_RATEINFO = 15210
PROTO_MAP[SC_STATUE_RATEINFO] = "sc_statue_rateinfo"

CS_STATUE_AREAINFO = 15211
PROTO_MAP[CS_STATUE_AREAINFO] = "cs_statue_areainfo"

SC_STATUE_AREAINFO = 15212
PROTO_MAP[SC_STATUE_AREAINFO] = "sc_statue_areainfo"

CS_BIOGBATTLE_INFO = 15303
PROTO_MAP[CS_BIOGBATTLE_INFO] = "cs_biogbattle_info"

SC_BIOGBATTLE_INFO = 15304
PROTO_MAP[SC_BIOGBATTLE_INFO] = "sc_biogbattle_info"

CS_BIOGBATTLE_SELECT = 15305
PROTO_MAP[CS_BIOGBATTLE_SELECT] = "cs_biogbattle_select"

SC_BIOGBATTLE_SELECT = 15306
PROTO_MAP[SC_BIOGBATTLE_SELECT] = "sc_biogbattle_select"

SC_BIOGBATTLE_SHOPOPEN = 15308
PROTO_MAP[SC_BIOGBATTLE_SHOPOPEN] = "sc_biogbattle_shopopen"

CS_BIOGBATTLE_SHOPCLOSE = 15309
PROTO_MAP[CS_BIOGBATTLE_SHOPCLOSE] = "cs_biogbattle_shopclose"

SC_BIOGBATTLE_SHOPCLOSE = 15310
PROTO_MAP[SC_BIOGBATTLE_SHOPCLOSE] = "sc_biogbattle_shopclose"

CS_BIOGBATTLE_EXCHANGE = 15311
PROTO_MAP[CS_BIOGBATTLE_EXCHANGE] = "cs_biogbattle_exchange"

SC_BIOGBATTLE_EXCHANGE = 15312
PROTO_MAP[SC_BIOGBATTLE_EXCHANGE] = "sc_biogbattle_exchange"

CS_BIOGBATTLE_SHOPREFRESH = 15313
PROTO_MAP[CS_BIOGBATTLE_SHOPREFRESH] = "cs_biogbattle_shoprefresh"

SC_BIOGBATTLE_SHOPREFRESH = 15314
PROTO_MAP[SC_BIOGBATTLE_SHOPREFRESH] = "sc_biogbattle_shoprefresh"

CS_BIOGBATTLE_CHAPTERINFO = 15317
PROTO_MAP[CS_BIOGBATTLE_CHAPTERINFO] = "cs_biogbattle_chapterinfo"

SC_BIOGBATTLE_CHAPTERINFO = 15318
PROTO_MAP[SC_BIOGBATTLE_CHAPTERINFO] = "sc_biogbattle_chapterinfo"

CS_BIOGBATTLE_FIGHT = 15319
PROTO_MAP[CS_BIOGBATTLE_FIGHT] = "cs_biogbattle_fight"

SC_BIOGBATTLE_FIGHT = 15320
PROTO_MAP[SC_BIOGBATTLE_FIGHT] = "sc_biogbattle_fight"

CS_BIOGBATTLE_OPENBOX = 15321
PROTO_MAP[CS_BIOGBATTLE_OPENBOX] = "cs_biogbattle_openbox"

SC_BIOGBATTLE_OPENBOX = 15322
PROTO_MAP[SC_BIOGBATTLE_OPENBOX] = "sc_biogbattle_openbox"

CS_BIOGBATTLE_DISPOSAL = 15325
PROTO_MAP[CS_BIOGBATTLE_DISPOSAL] = "cs_biogbattle_disposal"

SC_BIOGBATTLE_DISPOSAL = 15326
PROTO_MAP[SC_BIOGBATTLE_DISPOSAL] = "sc_biogbattle_disposal"

CS_WHEEL_STATE = 15401
PROTO_MAP[CS_WHEEL_STATE] = "cs_wheel_state"

SC_WHEEL_STATE = 15402
PROTO_MAP[SC_WHEEL_STATE] = "sc_wheel_state"

CS_WHEEL_INFO = 15403
PROTO_MAP[CS_WHEEL_INFO] = "cs_wheel_info"

SC_WHEEL_INFO = 15404
PROTO_MAP[SC_WHEEL_INFO] = "sc_wheel_info"

CS_WHEEL_PLAY = 15408
PROTO_MAP[CS_WHEEL_PLAY] = "cs_wheel_play"

SC_WHEEL_PLAY = 15409
PROTO_MAP[SC_WHEEL_PLAY] = "sc_wheel_play"

CS_WHEEL_DRAW = 15410
PROTO_MAP[CS_WHEEL_DRAW] = "cs_wheel_draw"

SC_WHEEL_DRAW = 15411
PROTO_MAP[SC_WHEEL_DRAW] = "sc_wheel_draw"

CS_WHEEL_RANK_LIST = 15412
PROTO_MAP[CS_WHEEL_RANK_LIST] = "cs_wheel_rank_list"

SC_WHEEL_RANK_LIST = 15413
PROTO_MAP[SC_WHEEL_RANK_LIST] = "sc_wheel_rank_list"

CS_WHEEL_LUCKY_MAN = 15415
PROTO_MAP[CS_WHEEL_LUCKY_MAN] = "cs_wheel_lucky_man"

SC_WHEEL_LUCKY_MAN = 15416
PROTO_MAP[SC_WHEEL_LUCKY_MAN] = "sc_wheel_lucky_man"

CS_WHEEL_CONFIG = 15417
PROTO_MAP[CS_WHEEL_CONFIG] = "cs_wheel_config"

SC_WHEEL_CONFIG = 15418
PROTO_MAP[SC_WHEEL_CONFIG] = "sc_wheel_config"

CS_DIGITALCORE_INFO = 15501
PROTO_MAP[CS_DIGITALCORE_INFO] = "cs_digitalcore_info"

SC_DIGITALCORE_INFO = 15502
PROTO_MAP[SC_DIGITALCORE_INFO] = "sc_digitalcore_info"

CS_DIGITALCORE_TUPO = 15505
PROTO_MAP[CS_DIGITALCORE_TUPO] = "cs_digitalcore_tupo"

SC_DIGITALCORE_TUPO = 15506
PROTO_MAP[SC_DIGITALCORE_TUPO] = "sc_digitalcore_tupo"

CS_DIGITALCORE_ACTIVATION = 15507
PROTO_MAP[CS_DIGITALCORE_ACTIVATION] = "cs_digitalcore_activation"

SC_DIGITALCORE_ACTIVATION = 15508
PROTO_MAP[SC_DIGITALCORE_ACTIVATION] = "sc_digitalcore_activation"

CS_DIGITALCORE_SELREPLACE = 15509
PROTO_MAP[CS_DIGITALCORE_SELREPLACE] = "cs_digitalcore_selreplace"

SC_DIGITALCORE_SELREPLACE = 15510
PROTO_MAP[SC_DIGITALCORE_SELREPLACE] = "sc_digitalcore_selreplace"

CS_CHICKEN_STATE = 15601
PROTO_MAP[CS_CHICKEN_STATE] = "cs_chicken_state"

SC_CHICKEN_STATE = 15602
PROTO_MAP[SC_CHICKEN_STATE] = "sc_chicken_state"

CS_CHICKEN_RANK_LIST = 15603
PROTO_MAP[CS_CHICKEN_RANK_LIST] = "cs_chicken_rank_list"

SC_CHICKEN_RANK_LIST = 15604
PROTO_MAP[SC_CHICKEN_RANK_LIST] = "sc_chicken_rank_list"

CS_CHICKEN_RANK_REWARD = 15606
PROTO_MAP[CS_CHICKEN_RANK_REWARD] = "cs_chicken_rank_reward"

SC_CHICKEN_RANK_REWARD = 15607
PROTO_MAP[SC_CHICKEN_RANK_REWARD] = "sc_chicken_rank_reward"

CS_CHICKEN_SIGN = 15608
PROTO_MAP[CS_CHICKEN_SIGN] = "cs_chicken_sign"

SC_CHICKEN_SIGN = 15609
PROTO_MAP[SC_CHICKEN_SIGN] = "sc_chicken_sign"

SC_CHICKEN_BEGIN = 15610
PROTO_MAP[SC_CHICKEN_BEGIN] = "sc_chicken_begin"

CS_CHICKEN_SET_LINE = 15611
PROTO_MAP[CS_CHICKEN_SET_LINE] = "cs_chicken_set_line"

SC_CHICKEN_SET_LINE = 15612
PROTO_MAP[SC_CHICKEN_SET_LINE] = "sc_chicken_set_line"

SC_CHICKEN_INIT = 15613
PROTO_MAP[SC_CHICKEN_INIT] = "sc_chicken_init"

CS_CHICKEN_FORT = 15618
PROTO_MAP[CS_CHICKEN_FORT] = "cs_chicken_fort"

SC_CHICKEN_FORT = 15619
PROTO_MAP[SC_CHICKEN_FORT] = "sc_chicken_fort"

CS_CHICKEN_REPLAY = 15620
PROTO_MAP[CS_CHICKEN_REPLAY] = "cs_chicken_replay"

SC_CHICKEN_REPLAY = 15621
PROTO_MAP[SC_CHICKEN_REPLAY] = "sc_chicken_replay"

SC_CHICKEN_VIEW_REPLAY = 15623
PROTO_MAP[SC_CHICKEN_VIEW_REPLAY] = "sc_chicken_view_replay"

SC_CHICKEN_FORT_FIGHT = 15624
PROTO_MAP[SC_CHICKEN_FORT_FIGHT] = "sc_chicken_fort_fight"

SC_CHICKEN_FORT_FIGHT_WIN = 15625
PROTO_MAP[SC_CHICKEN_FORT_FIGHT_WIN] = "sc_chicken_fort_fight_win"

SC_CHICKEN_FORT_FIGHT_LOSE = 15626
PROTO_MAP[SC_CHICKEN_FORT_FIGHT_LOSE] = "sc_chicken_fort_fight_lose"

SC_CHICKEN_WIN = 15627
PROTO_MAP[SC_CHICKEN_WIN] = "sc_chicken_win"

SC_CHICKEN_ROUND = 15628
PROTO_MAP[SC_CHICKEN_ROUND] = "sc_chicken_round"

SC_CHICKEN_PLAY_SYNC = 15629
PROTO_MAP[SC_CHICKEN_PLAY_SYNC] = "sc_chicken_play_sync"

CS_CHICKEN_VIEW_REPLAY = 15630
PROTO_MAP[CS_CHICKEN_VIEW_REPLAY] = "cs_chicken_view_replay"

CS_CHICKEN_SIGN_CANCEL = 15632
PROTO_MAP[CS_CHICKEN_SIGN_CANCEL] = "cs_chicken_sign_cancel"

SC_CHICKEN_SIGN_CANCEL = 15633
PROTO_MAP[SC_CHICKEN_SIGN_CANCEL] = "sc_chicken_sign_cancel"

CS_CHICKEN_ASK = 15634
PROTO_MAP[CS_CHICKEN_ASK] = "cs_chicken_ask"

SC_CHICKEN_ASK = 15635
PROTO_MAP[SC_CHICKEN_ASK] = "sc_chicken_ask"

CS_CHICKEN_INIT = 15636
PROTO_MAP[CS_CHICKEN_INIT] = "cs_chicken_init"

CS_CHICKEN_MOVE = 15637
PROTO_MAP[CS_CHICKEN_MOVE] = "cs_chicken_move"

SC_CHICKEN_MOVE = 15638
PROTO_MAP[SC_CHICKEN_MOVE] = "sc_chicken_move"

SC_CHICKEN_SUMMARY_SYNC = 15639
PROTO_MAP[SC_CHICKEN_SUMMARY_SYNC] = "sc_chicken_summary_sync"

SC_CHICKEN_WAIT_SYNC = 15640
PROTO_MAP[SC_CHICKEN_WAIT_SYNC] = "sc_chicken_wait_sync"

SC_CHICKEN_SIGN_SYNC = 15641
PROTO_MAP[SC_CHICKEN_SIGN_SYNC] = "sc_chicken_sign_sync"

CS_CHICKEN_BOX = 15642
PROTO_MAP[CS_CHICKEN_BOX] = "cs_chicken_box"

SC_CHICKEN_BOX = 15643
PROTO_MAP[SC_CHICKEN_BOX] = "sc_chicken_box"

CS_CHICKEN_BOX_DRAW = 15644
PROTO_MAP[CS_CHICKEN_BOX_DRAW] = "cs_chicken_box_draw"

SC_CHICKEN_BOX_DRAW = 15645
PROTO_MAP[SC_CHICKEN_BOX_DRAW] = "sc_chicken_box_draw"

CS_CHICKEN_LEAVE = 15646
PROTO_MAP[CS_CHICKEN_LEAVE] = "cs_chicken_leave"

SC_CHICKEN_LEAVE = 15647
PROTO_MAP[SC_CHICKEN_LEAVE] = "sc_chicken_leave"

CS_CHICKEN_EAT_BUF = 15648
PROTO_MAP[CS_CHICKEN_EAT_BUF] = "cs_chicken_eat_buf"

SC_CHICKEN_EAT_BUF = 15649
PROTO_MAP[SC_CHICKEN_EAT_BUF] = "sc_chicken_eat_buf"

CS_PRECIOUS_INFO = 15701
PROTO_MAP[CS_PRECIOUS_INFO] = "cs_precious_info"

SC_PRECIOUS_INFO = 15702
PROTO_MAP[SC_PRECIOUS_INFO] = "sc_precious_info"

CS_PRECIOUS_IMBUE = 15704
PROTO_MAP[CS_PRECIOUS_IMBUE] = "cs_precious_imbue"

SC_PRECIOUS_IMBUE = 15705
PROTO_MAP[SC_PRECIOUS_IMBUE] = "sc_precious_imbue"

CS_PRECIOUS_UNLOAD = 15706
PROTO_MAP[CS_PRECIOUS_UNLOAD] = "cs_precious_unload"

SC_PRECIOUS_UNLOAD = 15707
PROTO_MAP[SC_PRECIOUS_UNLOAD] = "sc_precious_unload"

CS_PRECIOUS_UPRANK = 15708
PROTO_MAP[CS_PRECIOUS_UPRANK] = "cs_precious_uprank"

SC_PRECIOUS_UPRANK = 15709
PROTO_MAP[SC_PRECIOUS_UPRANK] = "sc_precious_uprank"

SC_PRECIOUS_NOTIFY = 15710
PROTO_MAP[SC_PRECIOUS_NOTIFY] = "sc_precious_notify"

CS_GATHER_INFO = 15801
PROTO_MAP[CS_GATHER_INFO] = "cs_gather_info"

SC_GATHER_INFO = 15802
PROTO_MAP[SC_GATHER_INFO] = "sc_gather_info"

CS_GATHER_NPC_UPLEVEL = 15803
PROTO_MAP[CS_GATHER_NPC_UPLEVEL] = "cs_gather_npc_uplevel"

SC_GATHER_NPC_UPLEVEL = 15804
PROTO_MAP[SC_GATHER_NPC_UPLEVEL] = "sc_gather_npc_uplevel"

CS_GATHER_NPC_THROUGH = 15805
PROTO_MAP[CS_GATHER_NPC_THROUGH] = "cs_gather_npc_through"

SC_GATHER_NPC_THROUGH = 15806
PROTO_MAP[SC_GATHER_NPC_THROUGH] = "sc_gather_npc_through"

CS_GATHER_ENHANCE = 15807
PROTO_MAP[CS_GATHER_ENHANCE] = "cs_gather_enhance"

SC_GATHER_ENHANCE = 15808
PROTO_MAP[SC_GATHER_ENHANCE] = "sc_gather_enhance"

CS_GATHER_NPC_UNLOCK = 15809
PROTO_MAP[CS_GATHER_NPC_UNLOCK] = "cs_gather_npc_unlock"

SC_GATHER_NPC_UNLOCK = 15810
PROTO_MAP[SC_GATHER_NPC_UNLOCK] = "sc_gather_npc_unlock"

CS_GATHER_ENHANCE_RESET = 15811
PROTO_MAP[CS_GATHER_ENHANCE_RESET] = "cs_gather_enhance_reset"

SC_GATHER_ENHANCE_RESET = 15812
PROTO_MAP[SC_GATHER_ENHANCE_RESET] = "sc_gather_enhance_reset"

SC_GATHER_NOTIFY = 15813
PROTO_MAP[SC_GATHER_NOTIFY] = "sc_gather_notify"

SC_GATHER_NPC_NOTIFY = 15814
PROTO_MAP[SC_GATHER_NPC_NOTIFY] = "sc_gather_npc_notify"

CS_GATHER_FIGHT_REQUEST = 15818
PROTO_MAP[CS_GATHER_FIGHT_REQUEST] = "cs_gather_fight_request"

SC_GATHER_FIGHT_REQUEST = 15819
PROTO_MAP[SC_GATHER_FIGHT_REQUEST] = "sc_gather_fight_request"

CS_GATHER_FIGHT_REPORT = 15820
PROTO_MAP[CS_GATHER_FIGHT_REPORT] = "cs_gather_fight_report"

SC_GATHER_FIGHT_REPORT = 15821
PROTO_MAP[SC_GATHER_FIGHT_REPORT] = "sc_gather_fight_report"

CS_HORSE_INFO = 15901
PROTO_MAP[CS_HORSE_INFO] = "cs_horse_info"

SC_HORSE_INFO = 15902
PROTO_MAP[SC_HORSE_INFO] = "sc_horse_info"

CS_HORSE_SELECTINFO = 15904
PROTO_MAP[CS_HORSE_SELECTINFO] = "cs_horse_selectinfo"

SC_HORSE_SELECTINFO = 15905
PROTO_MAP[SC_HORSE_SELECTINFO] = "sc_horse_selectinfo"

CS_HORSE_GUESSINFO = 15907
PROTO_MAP[CS_HORSE_GUESSINFO] = "cs_horse_guessinfo"

SC_HORSE_GUESSINFO = 15908
PROTO_MAP[SC_HORSE_GUESSINFO] = "sc_horse_guessinfo"

CS_HORSE_INSPIREINFO = 15911
PROTO_MAP[CS_HORSE_INSPIREINFO] = "cs_horse_inspireinfo"

SC_HORSE_INSPIREINFO = 15912
PROTO_MAP[SC_HORSE_INSPIREINFO] = "sc_horse_inspireinfo"

SC_HORSE_NOTIFY_INSPIRE_FLY = 15913
PROTO_MAP[SC_HORSE_NOTIFY_INSPIRE_FLY] = "sc_horse_notify_inspire_fly"

CS_HORSE_REAL_MATCH = 15916
PROTO_MAP[CS_HORSE_REAL_MATCH] = "cs_horse_real_match"

SC_HORSE_REAL_MATCH = 15917
PROTO_MAP[SC_HORSE_REAL_MATCH] = "sc_horse_real_match"

CS_HORSE_SELECTION = 15918
PROTO_MAP[CS_HORSE_SELECTION] = "cs_horse_selection"

SC_HORSE_SELECTION = 15919
PROTO_MAP[SC_HORSE_SELECTION] = "sc_horse_selection"

CS_HORSE_PRECOM_GUESS = 15920
PROTO_MAP[CS_HORSE_PRECOM_GUESS] = "cs_horse_precom_guess"

SC_HORSE_PRECOM_GUESS = 15921
PROTO_MAP[SC_HORSE_PRECOM_GUESS] = "sc_horse_precom_guess"

CS_HORSE_INSPIRE = 15922
PROTO_MAP[CS_HORSE_INSPIRE] = "cs_horse_inspire"

SC_HORSE_INSPIRE = 15923
PROTO_MAP[SC_HORSE_INSPIRE] = "sc_horse_inspire"

SC_HORSE_NOTIFY_STAGE = 15924
PROTO_MAP[SC_HORSE_NOTIFY_STAGE] = "sc_horse_notify_stage"

CS_HORSE_LEAVE = 15925
PROTO_MAP[CS_HORSE_LEAVE] = "cs_horse_leave"

SC_HORSE_LEAVE = 15926
PROTO_MAP[SC_HORSE_LEAVE] = "sc_horse_leave"

CS_HORSE_RECORD = 15927
PROTO_MAP[CS_HORSE_RECORD] = "cs_horse_record"

SC_HORSE_RECORD = 15928
PROTO_MAP[SC_HORSE_RECORD] = "sc_horse_record"

CS_HORSE_ENTER = 15932
PROTO_MAP[CS_HORSE_ENTER] = "cs_horse_enter"

SC_HORSE_ENTER = 15933
PROTO_MAP[SC_HORSE_ENTER] = "sc_horse_enter"

CS_FEXTREME_BOX = 16001
PROTO_MAP[CS_FEXTREME_BOX] = "cs_fextreme_box"

SC_FEXTREME_BOX = 16002
PROTO_MAP[SC_FEXTREME_BOX] = "sc_fextreme_box"

CS_HOMEFIGHT_INFO = 16101
PROTO_MAP[CS_HOMEFIGHT_INFO] = "cs_homefight_info"

SC_HOMEFIGHT_INFO = 16102
PROTO_MAP[SC_HOMEFIGHT_INFO] = "sc_homefight_info"

CS_HOMEFIGHT_TEAM = 16103
PROTO_MAP[CS_HOMEFIGHT_TEAM] = "cs_homefight_team"

SC_HOMEFIGHT_TEAM = 16104
PROTO_MAP[SC_HOMEFIGHT_TEAM] = "sc_homefight_team"

CS_HOMEFIGHT_DUNGEON = 16106
PROTO_MAP[CS_HOMEFIGHT_DUNGEON] = "cs_homefight_dungeon"

SC_HOMEFIGHT_DUNGEON = 16107
PROTO_MAP[SC_HOMEFIGHT_DUNGEON] = "sc_homefight_dungeon"

CS_HOMEFIGHT_FORT = 16109
PROTO_MAP[CS_HOMEFIGHT_FORT] = "cs_homefight_fort"

SC_HOMEFIGHT_FORT = 16110
PROTO_MAP[SC_HOMEFIGHT_FORT] = "sc_homefight_fort"

CS_HOMEFIGHT_SHOP = 16112
PROTO_MAP[CS_HOMEFIGHT_SHOP] = "cs_homefight_shop"

SC_HOMEFIGHT_SHOP = 16113
PROTO_MAP[SC_HOMEFIGHT_SHOP] = "sc_homefight_shop"

CS_HOMEFIGHT_CREATE_TEAM = 16115
PROTO_MAP[CS_HOMEFIGHT_CREATE_TEAM] = "cs_homefight_create_team"

SC_HOMEFIGHT_CREATE_TEAM = 16116
PROTO_MAP[SC_HOMEFIGHT_CREATE_TEAM] = "sc_homefight_create_team"

CS_HOMEFIGHT_QUICK_JOIN = 16118
PROTO_MAP[CS_HOMEFIGHT_QUICK_JOIN] = "cs_homefight_quick_join"

SC_HOMEFIGHT_QUICK_JOIN = 16119
PROTO_MAP[SC_HOMEFIGHT_QUICK_JOIN] = "sc_homefight_quick_join"

CS_HOMEFIGHT_JOIN_TEAM = 16120
PROTO_MAP[CS_HOMEFIGHT_JOIN_TEAM] = "cs_homefight_join_team"

SC_HOMEFIGHT_JOIN_TEAM = 16121
PROTO_MAP[SC_HOMEFIGHT_JOIN_TEAM] = "sc_homefight_join_team"

CS_HOMEFIGHT_SET_OPEN = 16122
PROTO_MAP[CS_HOMEFIGHT_SET_OPEN] = "cs_homefight_set_open"

SC_HOMEFIGHT_SET_OPEN = 16123
PROTO_MAP[SC_HOMEFIGHT_SET_OPEN] = "sc_homefight_set_open"

CS_HOMEFIGHT_KICK = 16124
PROTO_MAP[CS_HOMEFIGHT_KICK] = "cs_homefight_kick"

SC_HOMEFIGHT_KICK = 16125
PROTO_MAP[SC_HOMEFIGHT_KICK] = "sc_homefight_kick"

CS_HOMEFIGHT_MARK_READY = 16126
PROTO_MAP[CS_HOMEFIGHT_MARK_READY] = "cs_homefight_mark_ready"

SC_HOMEFIGHT_MARK_READY = 16127
PROTO_MAP[SC_HOMEFIGHT_MARK_READY] = "sc_homefight_mark_ready"

CS_HOMEFIGHT_NEW_TEAM = 16128
PROTO_MAP[CS_HOMEFIGHT_NEW_TEAM] = "cs_homefight_new_team"

SC_HOMEFIGHT_NEW_TEAM = 16129
PROTO_MAP[SC_HOMEFIGHT_NEW_TEAM] = "sc_homefight_new_team"

CS_HOMEFIGHT_CHANGE_GER = 16130
PROTO_MAP[CS_HOMEFIGHT_CHANGE_GER] = "cs_homefight_change_ger"

SC_HOMEFIGHT_CHANGE_GER = 16131
PROTO_MAP[SC_HOMEFIGHT_CHANGE_GER] = "sc_homefight_change_ger"

CS_HOMEFIGHT_SET_LEVEL = 16132
PROTO_MAP[CS_HOMEFIGHT_SET_LEVEL] = "cs_homefight_set_level"

SC_HOMEFIGHT_SET_LEVEL = 16133
PROTO_MAP[SC_HOMEFIGHT_SET_LEVEL] = "sc_homefight_set_level"

CS_HOMEFIGHT_START = 16134
PROTO_MAP[CS_HOMEFIGHT_START] = "cs_homefight_start"

SC_HOMEFIGHT_START = 16135
PROTO_MAP[SC_HOMEFIGHT_START] = "sc_homefight_start"

SC_HOMEFIGHT_TEAM_SYNC = 16136
PROTO_MAP[SC_HOMEFIGHT_TEAM_SYNC] = "sc_homefight_team_sync"

CS_HOMEFIGHT_MOVE = 16137
PROTO_MAP[CS_HOMEFIGHT_MOVE] = "cs_homefight_move"

SC_HOMEFIGHT_MOVE = 16138
PROTO_MAP[SC_HOMEFIGHT_MOVE] = "sc_homefight_move"

CS_HOMEFIGHT_BUY = 16139
PROTO_MAP[CS_HOMEFIGHT_BUY] = "cs_homefight_buy"

SC_HOMEFIGHT_BUY = 16140
PROTO_MAP[SC_HOMEFIGHT_BUY] = "sc_homefight_buy"

CS_HOMEFIGHT_REQUEST = 16141
PROTO_MAP[CS_HOMEFIGHT_REQUEST] = "cs_homefight_request"

SC_HOMEFIGHT_REQUEST = 16142
PROTO_MAP[SC_HOMEFIGHT_REQUEST] = "sc_homefight_request"

CS_HOMEFIGHT_REPORT = 16143
PROTO_MAP[CS_HOMEFIGHT_REPORT] = "cs_homefight_report"

SC_HOMEFIGHT_REPORT = 16144
PROTO_MAP[SC_HOMEFIGHT_REPORT] = "sc_homefight_report"

CS_HOMEFIGHT_FIGHT_BOSS = 16145
PROTO_MAP[CS_HOMEFIGHT_FIGHT_BOSS] = "cs_homefight_fight_boss"

SC_HOMEFIGHT_FIGHT_BOSS = 16146
PROTO_MAP[SC_HOMEFIGHT_FIGHT_BOSS] = "sc_homefight_fight_boss"

SC_HOMEFIGHT_KICK_NOTIFY = 16147
PROTO_MAP[SC_HOMEFIGHT_KICK_NOTIFY] = "sc_homefight_kick_notify"

CS_HOMEFIGHT_BACK = 16148
PROTO_MAP[CS_HOMEFIGHT_BACK] = "cs_homefight_back"

SC_HOMEFIGHT_BACK = 16149
PROTO_MAP[SC_HOMEFIGHT_BACK] = "sc_homefight_back"

SC_HOMEFIGHT_DUNGEON_NOTIFY = 16150
PROTO_MAP[SC_HOMEFIGHT_DUNGEON_NOTIFY] = "sc_homefight_dungeon_notify"

SC_HOMEFIGHT_ROLE_NOTIFY = 16151
PROTO_MAP[SC_HOMEFIGHT_ROLE_NOTIFY] = "sc_homefight_role_notify"

CS_HOMEFIGHT_BOSS = 16152
PROTO_MAP[CS_HOMEFIGHT_BOSS] = "cs_homefight_boss"

SC_HOMEFIGHT_BOSS = 16153
PROTO_MAP[SC_HOMEFIGHT_BOSS] = "sc_homefight_boss"

CS_HOMEFIGHT_LEAVE = 16154
PROTO_MAP[CS_HOMEFIGHT_LEAVE] = "cs_homefight_leave"

SC_HOMEFIGHT_LEAVE = 16155
PROTO_MAP[SC_HOMEFIGHT_LEAVE] = "sc_homefight_leave"

CS_HOMEFIGHT_INVITE = 16158
PROTO_MAP[CS_HOMEFIGHT_INVITE] = "cs_homefight_invite"

SC_HOMEFIGHT_INVITE = 16159
PROTO_MAP[SC_HOMEFIGHT_INVITE] = "sc_homefight_invite"

SC_HOMEFIGHT_END = 16160
PROTO_MAP[SC_HOMEFIGHT_END] = "sc_homefight_end"

SC_HOMEFIGHT_STATE = 16161
PROTO_MAP[SC_HOMEFIGHT_STATE] = "sc_homefight_state"

SC_HOMEFIGHT_BATTLE_END = 16162
PROTO_MAP[SC_HOMEFIGHT_BATTLE_END] = "sc_homefight_battle_end"

CS_CHOICEFIGHT_INFO = 16201
PROTO_MAP[CS_CHOICEFIGHT_INFO] = "cs_choicefight_info"

SC_CHOICEFIGHT_INFO = 16202
PROTO_MAP[SC_CHOICEFIGHT_INFO] = "sc_choicefight_info"

CS_CHOICEFIGHT_ACTIVE = 16203
PROTO_MAP[CS_CHOICEFIGHT_ACTIVE] = "cs_choicefight_active"

SC_CHOICEFIGHT_ACTIVE = 16204
PROTO_MAP[SC_CHOICEFIGHT_ACTIVE] = "sc_choicefight_active"

SC_CHOICEFIGHT_RECOVER = 16205
PROTO_MAP[SC_CHOICEFIGHT_RECOVER] = "sc_choicefight_recover"

CS_CHOICEFIGHT_SET_LINE = 16206
PROTO_MAP[CS_CHOICEFIGHT_SET_LINE] = "cs_choicefight_set_line"

SC_CHOICEFIGHT_SET_LINE = 16207
PROTO_MAP[SC_CHOICEFIGHT_SET_LINE] = "sc_choicefight_set_line"

CS_CHOICEFIGHT_LINE = 16208
PROTO_MAP[CS_CHOICEFIGHT_LINE] = "cs_choicefight_line"

SC_CHOICEFIGHT_LINE = 16209
PROTO_MAP[SC_CHOICEFIGHT_LINE] = "sc_choicefight_line"

CS_CHOICEFIGHT_FIGHT_REQUEST = 16210
PROTO_MAP[CS_CHOICEFIGHT_FIGHT_REQUEST] = "cs_choicefight_fight_request"

SC_CHOICEFIGHT_FIGHT_REQUEST = 16211
PROTO_MAP[SC_CHOICEFIGHT_FIGHT_REQUEST] = "sc_choicefight_fight_request"

CS_CHOICEFIGHT_REPORT = 16212
PROTO_MAP[CS_CHOICEFIGHT_REPORT] = "cs_choicefight_report"

SC_CHOICEFIGHT_REPORT = 16213
PROTO_MAP[SC_CHOICEFIGHT_REPORT] = "sc_choicefight_report"

CS_CHOICEFIGHT_RESET = 16214
PROTO_MAP[CS_CHOICEFIGHT_RESET] = "cs_choicefight_reset"

SC_CHOICEFIGHT_RESET = 16215
PROTO_MAP[SC_CHOICEFIGHT_RESET] = "sc_choicefight_reset"

CS_CHOICEFIGHT_BUY = 16216
PROTO_MAP[CS_CHOICEFIGHT_BUY] = "cs_choicefight_buy"

SC_CHOICEFIGHT_BUY = 16217
PROTO_MAP[SC_CHOICEFIGHT_BUY] = "sc_choicefight_buy"

CS_CHOICEFIGHT_HARD_BUY = 16218
PROTO_MAP[CS_CHOICEFIGHT_HARD_BUY] = "cs_choicefight_hard_buy"

SC_CHOICEFIGHT_HARD_BUY = 16219
PROTO_MAP[SC_CHOICEFIGHT_HARD_BUY] = "sc_choicefight_hard_buy"

CS_GERCARD_INFO = 16301
PROTO_MAP[CS_GERCARD_INFO] = "cs_gercard_info"

SC_GERCARD_INFO = 16302
PROTO_MAP[SC_GERCARD_INFO] = "sc_gercard_info"

CS_GERCARD_UNLOCK = 16305
PROTO_MAP[CS_GERCARD_UNLOCK] = "cs_gercard_unlock"

SC_GERCARD_UNLOCK = 16306
PROTO_MAP[SC_GERCARD_UNLOCK] = "sc_gercard_unlock"

CS_GERCARD_WASH = 16307
PROTO_MAP[CS_GERCARD_WASH] = "cs_gercard_wash"

SC_GERCARD_WASH = 16308
PROTO_MAP[SC_GERCARD_WASH] = "sc_gercard_wash"

CS_GERCARD_CHOSE = 16309
PROTO_MAP[CS_GERCARD_CHOSE] = "cs_gercard_chose"

SC_GERCARD_CHOSE = 16310
PROTO_MAP[SC_GERCARD_CHOSE] = "sc_gercard_chose"

CS_GERCARD_CLEAN = 16311
PROTO_MAP[CS_GERCARD_CLEAN] = "cs_gercard_clean"

SC_GERCARD_CLEAN = 16312
PROTO_MAP[SC_GERCARD_CLEAN] = "sc_gercard_clean"

CS_GERCARD_LAST = 16313
PROTO_MAP[CS_GERCARD_LAST] = "cs_gercard_last"

SC_GERCARD_LAST = 16314
PROTO_MAP[SC_GERCARD_LAST] = "sc_gercard_last"

CS_TEST_MESSAGE = 32601
PROTO_MAP[CS_TEST_MESSAGE] = "cs_test_message"

SC_TEST_MESSAGE = 32602
PROTO_MAP[SC_TEST_MESSAGE] = "sc_test_message"
