---------------------------------------------------------------------
-- @author wangyida
-- @copyright (C) 2018, <SKYMOONS>
-- @doc
--
-- @end
-- Created : 10. 七月 2018 17:02
---------------------------------------------------------------------

return {
    [1001] = { notice_id = 1001,
               notice_title = "标题1",
               notice_content = "内容1",
               notice_pic = "pic1",
               start_time = 1480921524,
               end_time = 1481921524
    },
    [1002] = { notice_id = 1002,
               notice_title = "标题1",
               notice_content = "内容",
               notice_pic = "pic1",
               start_time = 1480921524,
               end_time = 1481921524
    }
}
