---------------------------------------------------------------------
-- @author wangyida
-- @copyright (C) 2018, <SKYMOONS>
-- @doc
--
-- @end
-- Created : 06. 七月 2018 12:28
---------------------------------------------------------------------



--local state = {gate=nil, addr = "", login_state = false, watch_dog = nil, fd = nil,
--    roleid = nil, }

local role_state = {}


function role_state.init()
    return {}
end

return role_state