---------------------------------------------------------------------
-- @author wangyida
-- @copyright (C) 2018, <SKYMOONS>
-- @doc
--
-- @end
-- Created : 14. 七月 2018 18:27
---------------------------------------------------------------------

CONFIG = {
    data_notice = "data_notice",
    data_money = "data_money",
    data_route = "data_route",
    data_sign = "data_sign",
    data_common = "data_common",
    data_role_uplevel = "data_role_uplevel",
}

SETTING = {
    setting = "setting",
}