---------------------------------------------------------------------
-- @author wangyida
-- @copyright (C) 2018, <SKYMOONS>
-- @doc
--
-- @end
-- Created : 05. 七月 2018 19:08
---------------------------------------------------------------------
-- 内存中的key值和数据库表名的对应关系
DATABASE_TABLES = {
    role_info  = "role_info",
    money_info = "role_money",
    rmail_info = "role_mail",
    mail_info  = "mail_info",
    ger_info   = "role_ger",
    role_extra = "role_extra",
    sign_info  = "role_sign",
}

SHARE_TABLES = {
    role_online = "role_online",
    role_public = "role_public",
    ban_list    = "ban_list",
}

ID_TYPE_LIST = {
    id_type_role    = "id_type_role",
    id_type_family  = "id_type_family",
    id_type_ger     = "id_type_ger",
    id_type_equip   = "id_type_equip",
    id_type_mail    = "id_type_mail",
    id_type_hist    = "id_type_hist",
    id_type_message = "id_type_message",
    id_type_common  = "id_type_common",
    id_type_frdmsg  = "id_type_frdmsg",
    id_type_chaser  = "id_type_chaser",
}