---------------------------------------------------------------------
-- @author wangyida
-- @copyright (C) 2018, <SKYMOONS>
-- @doc
--
-- @end
-- Created : 09. 七月 2018 19:55
---------------------------------------------------------------------

SERVICE = {
    id_service = ".id_server",
    db_service = ".db_server",
    mail_service = ".mail_service",
    config_service = ".config_service",
    web_service = ".web_service",
    gate_service = ".gate_service"
}

MASTER_SERVICE = {

}